spring.application.name=listle
server.port=8080

# DataSource (H2)
spring.datasource.url=jdbc:h2:mem:listle;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Console H2 (pratique en dev)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console