DELETE FROM daily_categories;
DELETE FROM category_words;
DELETE FROM categories;

INSERT INTO categories (id, slug, name, difficulty, active)
SELECT
(substr(md5(v.slug), 1, 8) || '-' || substr(md5(v.slug), 9, 4) || '-' || substr(md5(v.slug), 13, 4) || '-' || substr(md5(v.slug), 17, 4) || '-' || substr(md5(v.slug), 21, 12))::uuid,
v.slug,
v.name,
v.difficulty,
v.active
FROM (
VALUES
('fruits', 'Fruits', 1, true),
('pays', 'Pays', 2, true),
('legumes', 'Legumes', 1, true),
('couleurs', 'Couleurs', 1, true),
('sports', 'Sports', 2, true),
('metiers', 'Metiers', 2, true),
('capitales', 'Capitales', 3, true),
('instruments', 'Instruments', 2, true),
('vehicules', 'Vehicules', 1, true),
('vetements', 'Vetements', 1, true),
('boissons', 'Boissons', 1, true),
('desserts', 'Desserts', 1, true),
('jeux_video', 'Jeux video', 2, true),
('sciences', 'Sciences', 3, true),
('musique', 'Musique', 2, true),
('fromages', 'Fromages', 2, true),
('elements_chimiques', 'Elements chimiques', 3, true),
('constellations', 'Constellations', 3, true),
('danses', 'Danses', 2, true),
('langues', 'Langues', 2, true),
('epices', 'Epices', 2, true),
('cocktails', 'Cocktails', 2, true),
('arts_martiaux', 'Arts martiaux', 2, true),
('monnaies', 'Monnaies', 2, true),
('meubles', 'Meubles', 1, true),
('arbres', 'Arbres', 2, true),
('pierres_precieuses', 'Pierres precieuses', 2, true)
) AS v(slug, name, difficulty, active)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
difficulty = EXCLUDED.difficulty,
active = EXCLUDED.active;

UPDATE categories AS c SET
  source_type = 'WIKIDATA',
  source_ref = s.qid,
  source_min_sitelinks = s.min_sitelinks
FROM (
VALUES
  ('fruits',      'Q3314483', 25),
  ('legumes',     'Q11004',   18),
  ('couleurs',    'Q1075',    22),
  ('pays',        'Q6256',    20),
  ('capitales',   'Q5119',    20),
  ('sports',      'Q349',     30),
  ('metiers',     'Q28640',   30),
  ('instruments', 'Q34379',   25),
  ('vehicules',   'Q42889',   35),
  ('vetements',   'Q11460',   25),
  ('boissons',    'Q40050',   20),
  ('desserts',    'Q182940',  12),
  ('jeux_video',  'Q7889',    45),
  ('sciences',    'Q336',     45),
  ('musique',     'Q188451',  30),
  ('fromages',           'Q10943', 6),
  ('elements_chimiques', 'Q11344', 15),
  ('constellations',     'Q8928',  12),
  ('danses',             'Q11639', 12),
  ('langues',            'Q34770', 40),
  ('epices',             'Q42527', 6),
  ('cocktails',          'Q134768', 6),
  ('arts_martiaux',      'Q11417', 10),
  ('monnaies',           'Q8142',  25),
  ('meubles',            'Q14745', 12),
  ('arbres',             'Q10884', 22),
  ('pierres_precieuses', 'Q83437', 8)
) AS s(slug, qid, min_sitelinks)
WHERE c.slug = s.slug;

INSERT INTO category_words (id, category_id, label, normalized_label)
SELECT
(substr(md5(c.slug || ':' || w.normalized_label), 1, 8) || '-' || substr(md5(c.slug || ':' || w.normalized_label), 9, 4) || '-' || substr(md5(c.slug || ':' || w.normalized_label), 13, 4) || '-' || substr(md5(c.slug || ':' || w.normalized_label), 17, 4) || '-' || substr(md5(c.slug || ':' || w.normalized_label), 21, 12))::uuid,
c.id,
w.label,
w.normalized_label
FROM categories c
JOIN (
VALUES
('fruits', 'Pomme', 'pomme'),
('fruits', 'Banane', 'banane'),
('fruits', 'Orange', 'orange'),
('fruits', 'Poire', 'poire'),
('fruits', 'Mangue', 'mangue'),
('fruits', 'Fraise', 'fraise'),
('fruits', 'Framboise', 'framboise'),
('fruits', 'Myrtille', 'myrtille'),
('fruits', 'Ananas', 'ananas'),
('fruits', 'Cerise', 'cerise'),
('fruits', 'Abricot', 'abricot'),
('fruits', 'Peche', 'peche'),
('fruits', 'Prune', 'prune'),
('fruits', 'Citron', 'citron'),
('fruits', 'Kiwi', 'kiwi'),


('pays', 'France', 'france'),
('pays', 'Espagne', 'espagne'),
('pays', 'Italie', 'italie'),
('pays', 'Allemagne', 'allemagne'),
('pays', 'Portugal', 'portugal'),
('pays', 'Belgique', 'belgique'),
('pays', 'Suisse', 'suisse'),
('pays', 'Canada', 'canada'),
('pays', 'Mexique', 'mexique'),
('pays', 'Bresil', 'bresil'),
('pays', 'Argentine', 'argentine'),
('pays', 'Japon', 'japon'),
('pays', 'Inde', 'inde'),
('pays', 'Maroc', 'maroc'),
('pays', 'Egypte', 'egypte'),

('legumes', 'Carotte', 'carotte'),
('legumes', 'Tomate', 'tomate'),
('legumes', 'Courgette', 'courgette'),
('legumes', 'Aubergine', 'aubergine'),
('legumes', 'Poireau', 'poireau'),
('legumes', 'Oignon', 'oignon'),
('legumes', 'Ail', 'ail'),
('legumes', 'Pomme de terre', 'pomme de terre'),
('legumes', 'Poivron', 'poivron'),
('legumes', 'Concombre', 'concombre'),
('legumes', 'Radis', 'radis'),
('legumes', 'Navet', 'navet'),
('legumes', 'Chou', 'chou'),
('legumes', 'Brocoli', 'brocoli'),
('legumes', 'Epinard', 'epinard'),

('couleurs', 'Rouge', 'rouge'),
('couleurs', 'Bleu', 'bleu'),
('couleurs', 'Vert', 'vert'),
('couleurs', 'Jaune', 'jaune'),
('couleurs', 'Orange', 'orange'),
('couleurs', 'Violet', 'violet'),
('couleurs', 'Rose', 'rose'),
('couleurs', 'Marron', 'marron'),
('couleurs', 'Noir', 'noir'),
('couleurs', 'Blanc', 'blanc'),
('couleurs', 'Gris', 'gris'),
('couleurs', 'Turquoise', 'turquoise'),
('couleurs', 'Beige', 'beige'),
('couleurs', 'Doré', 'dore'),
('couleurs', 'Argenté', 'argente'),

('sports', 'Football', 'football'),
('sports', 'Basketball', 'basketball'),
('sports', 'Tennis', 'tennis'),
('sports', 'Rugby', 'rugby'),
('sports', 'Natation', 'natation'),
('sports', 'Cyclisme', 'cyclisme'),
('sports', 'Athletisme', 'athletisme'),
('sports', 'Judo', 'judo'),
('sports', 'Boxe', 'boxe'),
('sports', 'Escalade', 'escalade'),
('sports', 'Golf', 'golf'),
('sports', 'Volleyball', 'volleyball'),
('sports', 'Handball', 'handball'),
('sports', 'Badminton', 'badminton'),
('sports', 'Escrime', 'escrime'),

('metiers', 'Medecin', 'medecin'),
('metiers', 'Infirmier', 'infirmier'),
('metiers', 'Professeur', 'professeur'),
('metiers', 'Boulanger', 'boulanger'),
('metiers', 'Pompier', 'pompier'),
('metiers', 'Policier', 'policier'),
('metiers', 'Avocat', 'avocat'),
('metiers', 'Architecte', 'architecte'),
('metiers', 'Ingenieur', 'ingenieur'),
('metiers', 'Chauffeur', 'chauffeur'),
('metiers', 'Coiffeur', 'coiffeur'),
('metiers', 'Cuisinier', 'cuisinier'),
('metiers', 'Journaliste', 'journaliste'),
('metiers', 'Peintre', 'peintre'),
('metiers', 'Mecanicien', 'mecanicien'),

('capitales', 'Paris', 'paris'),
('capitales', 'Madrid', 'madrid'),
('capitales', 'Rome', 'rome'),
('capitales', 'Berlin', 'berlin'),
('capitales', 'Lisbonne', 'lisbonne'),
('capitales', 'Bruxelles', 'bruxelles'),
('capitales', 'Tokyo', 'tokyo'),
('capitales', 'Ottawa', 'ottawa'),
('capitales', 'Mexico', 'mexico'),
('capitales', 'Brasilia', 'brasilia'),
('capitales', 'Buenos Aires', 'buenos aires'),
('capitales', 'Rabat', 'rabat'),
('capitales', 'Le Caire', 'le caire'),
('capitales', 'Canberra', 'canberra'),
('capitales', 'Seoul', 'seoul'),

('instruments', 'Guitare', 'guitare'),
('instruments', 'Piano', 'piano'),
('instruments', 'Violon', 'violon'),
('instruments', 'Batterie', 'batterie'),
('instruments', 'Flute', 'flute'),
('instruments', 'Trompette', 'trompette'),
('instruments', 'Saxophone', 'saxophone'),
('instruments', 'Harpe', 'harpe'),
('instruments', 'Clarinette', 'clarinette'),
('instruments', 'Accordeon', 'accordeon'),
('instruments', 'Ukulele', 'ukulele'),
('instruments', 'Basse', 'basse'),
('instruments', 'Hautbois', 'hautbois'),
('instruments', 'Trombone', 'trombone'),
('instruments', 'Violoncelle', 'violoncelle'),

('vehicules', 'Voiture', 'voiture'),
('vehicules', 'Moto', 'moto'),
('vehicules', 'Camion', 'camion'),
('vehicules', 'Bus', 'bus'),
('vehicules', 'Train', 'train'),
('vehicules', 'Tramway', 'tramway'),
('vehicules', 'Avion', 'avion'),
('vehicules', 'Helicoptere', 'helicoptere'),
('vehicules', 'Bateau', 'bateau'),
('vehicules', 'Velo', 'velo'),
('vehicules', 'Trottinette', 'trottinette'),
('vehicules', 'Tracteur', 'tracteur'),
('vehicules', 'Fourgon', 'fourgon'),
('vehicules', 'Metro', 'metro'),
('vehicules', 'Navette', 'navette'),



('vetements', 'Chemise', 'chemise'),
('vetements', 'Tshirt', 'tshirt'),
('vetements', 'Pantalon', 'pantalon'),
('vetements', 'Jean', 'jean'),
('vetements', 'Robe', 'robe'),
('vetements', 'Jupe', 'jupe'),
('vetements', 'Manteau', 'manteau'),
('vetements', 'Veste', 'veste'),
('vetements', 'Pull', 'pull'),
('vetements', 'Echarpe', 'echarpe'),
('vetements', 'Bonnet', 'bonnet'),
('vetements', 'Chapeau', 'chapeau'),
('vetements', 'Chaussures', 'chaussures'),
('vetements', 'Sandales', 'sandales'),
('vetements', 'Ceinture', 'ceinture'),

('boissons', 'Eau', 'eau'),
('boissons', 'Limonade', 'limonade'),
('boissons', 'Jus', 'jus'),
('boissons', 'Cafe', 'cafe'),
('boissons', 'The', 'the'),
('boissons', 'Lait', 'lait'),
('boissons', 'Soda', 'soda'),
('boissons', 'Smoothie', 'smoothie'),
('boissons', 'Sirop', 'sirop'),
('boissons', 'Chocolat chaud', 'chocolat chaud'),
('boissons', 'Milkshake', 'milkshake'),
('boissons', 'Infusion', 'infusion'),
('boissons', 'Lassi', 'lassi'),
('boissons', 'Kefir', 'kefir'),
('boissons', 'Cappuccino', 'cappuccino'),

('desserts', 'Tarte', 'tarte'),
('desserts', 'Gateau', 'gateau'),
('desserts', 'Crepe', 'crepe'),
('desserts', 'Mousse', 'mousse'),
('desserts', 'Glace', 'glace'),
('desserts', 'Sorbet', 'sorbet'),
('desserts', 'Eclair', 'eclair'),
('desserts', 'Macaron', 'macaron'),
('desserts', 'Brownie', 'brownie'),
('desserts', 'Donut', 'donut'),
('desserts', 'Cookie', 'cookie'),
('desserts', 'Flan', 'flan'),
('desserts', 'Tiramisu', 'tiramisu'),
('desserts', 'Panna cotta', 'panna cotta'),
('desserts', 'Gaufre', 'gaufre'),



('jeux_video', 'Mario', 'mario'),
('jeux_video', 'Zelda', 'zelda'),
('jeux_video', 'Minecraft', 'minecraft'),
('jeux_video', 'Fortnite', 'fortnite'),
('jeux_video', 'Tetris', 'tetris'),
('jeux_video', 'Pacman', 'pacman'),
('jeux_video', 'Doom', 'doom'),
('jeux_video', 'Fifa', 'fifa'),
('jeux_video', 'Overwatch', 'overwatch'),
('jeux_video', 'Valorant', 'valorant'),
('jeux_video', 'Skyrim', 'skyrim'),
('jeux_video', 'Cyberpunk', 'cyberpunk'),
('jeux_video', 'Pokemon', 'pokemon'),
('jeux_video', 'Sonic', 'sonic'),
('jeux_video', 'Metroid', 'metroid'),

('sciences', 'Physique', 'physique'),
('sciences', 'Chimie', 'chimie'),
('sciences', 'Biologie', 'biologie'),
('sciences', 'Geologie', 'geologie'),
('sciences', 'Astronomie', 'astronomie'),
('sciences', 'Ecologie', 'ecologie'),
('sciences', 'Genetique', 'genetique'),
('sciences', 'Zoologie', 'zoologie'),
('sciences', 'Botanique', 'botanique'),
('sciences', 'Informatique', 'informatique'),
('sciences', 'Statistiques', 'statistiques'),
('sciences', 'Maths', 'maths'),
('sciences', 'Anatomie', 'anatomie'),
('sciences', 'Meteorologie', 'meteorologie'),
('sciences', 'Oceanographie', 'oceanographie'),

('musique', 'Rock', 'rock'),
('musique', 'Jazz', 'jazz'),
('musique', 'Rap', 'rap'),
('musique', 'Pop', 'pop'),
('musique', 'Electro', 'electro'),
('musique', 'Classique', 'classique'),
('musique', 'Reggae', 'reggae'),
('musique', 'Funk', 'funk'),
('musique', 'Soul', 'soul'),
('musique', 'Blues', 'blues'),
('musique', 'Metal', 'metal'),
('musique', 'Techno', 'techno'),
('musique', 'Disco', 'disco'),
('musique', 'Salsa', 'salsa'),
('musique', 'Country', 'country'),

('fruits', 'Raisin', 'raisin'),
('fruits', 'Pasteque', 'pasteque'),
('fruits', 'Melon', 'melon'),
('fruits', 'Grenade', 'grenade'),
('fruits', 'Figue', 'figue'),


('pays', 'Suede', 'suede'),
('pays', 'Norvege', 'norvege'),
('pays', 'Finlande', 'finlande'),
('pays', 'Chine', 'chine'),
('pays', 'Australie', 'australie'),

('legumes', 'Haricot', 'haricot'),
('legumes', 'Petit pois', 'petit pois'),
('legumes', 'Celeri', 'celeri'),
('legumes', 'Champignon', 'champignon'),
('legumes', 'Patate douce', 'patate douce'),

('couleurs', 'Indigo', 'indigo'),
('couleurs', 'Cyan', 'cyan'),
('couleurs', 'Ocre', 'ocre'),
('couleurs', 'Lavande', 'lavande'),
('couleurs', 'Magenta', 'magenta'),

('sports', 'Karate', 'karate'),
('sports', 'Surf', 'surf'),
('sports', 'Ski', 'ski'),
('sports', 'Patinage', 'patinage'),
('sports', 'Triathlon', 'triathlon'),

('metiers', 'Pharmacien', 'pharmacien'),
('metiers', 'Dentiste', 'dentiste'),
('metiers', 'Veterinaire', 'veterinaire'),
('metiers', 'Developpeur', 'developpeur'),
('metiers', 'Plombier', 'plombier'),

('capitales', 'Stockholm', 'stockholm'),
('capitales', 'Oslo', 'oslo'),
('capitales', 'Helsinki', 'helsinki'),
('capitales', 'Pekin', 'pekin'),
('capitales', 'Wellington', 'wellington'),

('instruments', 'Mandoline', 'mandoline'),
('instruments', 'Xylophone', 'xylophone'),
('instruments', 'Banjo', 'banjo'),
('instruments', 'Tambourin', 'tambourin'),
('instruments', 'Cornemuse', 'cornemuse'),

('vehicules', 'Scooter', 'scooter'),
('vehicules', 'Kayak', 'kayak'),
('vehicules', 'Canoe', 'canoe'),
('vehicules', 'Zeppelin', 'zeppelin'),
('vehicules', 'Remorque', 'remorque'),



('vetements', 'Gants', 'gants'),
('vetements', 'Chaussettes', 'chaussettes'),
('vetements', 'Short', 'short'),
('vetements', 'Blazer', 'blazer'),
('vetements', 'Pyjama', 'pyjama'),

('boissons', 'Eau gazeuse', 'eau gazeuse'),
('boissons', 'Jus pomme', 'jus pomme'),
('boissons', 'Jus orange', 'jus orange'),
('boissons', 'Matcha', 'matcha'),
('boissons', 'Cidre', 'cidre'),
('boissons', 'Coca Cola', 'coca cola'),
('boissons', 'Pepsi', 'pepsi'),
('boissons', 'Fanta', 'fanta'),
('boissons', 'Sprite', 'sprite'),
('boissons', 'Orangina', 'orangina'),
('boissons', 'Red Bull', 'red bull'),
('boissons', 'Monster', 'monster'),
('boissons', 'Lipton Ice Tea', 'lipton ice tea'),
('boissons', 'Oasis', 'oasis'),
('boissons', 'Schweppes', 'schweppes'),
('boissons', 'Perrier', 'perrier'),
('boissons', 'Evian', 'evian'),
('boissons', 'Badoit', 'badoit'),
('boissons', 'San Pellegrino', 'san pellegrino'),
('boissons', 'Tropicana', 'tropicana'),
('boissons', 'Capri Sun', 'capri sun'),
('boissons', 'Gatorade', 'gatorade'),
('boissons', 'Powerade', 'powerade'),

('desserts', 'Millefeuille', 'millefeuille'),
('desserts', 'Profiterole', 'profiterole'),
('desserts', 'Meringue', 'meringue'),
('desserts', 'Cheesecake', 'cheesecake'),
('desserts', 'Clafoutis', 'clafoutis'),



('jeux_video', 'Halo', 'halo'),
('jeux_video', 'Portal', 'portal'),
('jeux_video', 'Celeste', 'celeste'),
('jeux_video', 'Hades', 'hades'),
('jeux_video', 'Uncharted', 'uncharted'),

('sciences', 'Microbiologie', 'microbiologie'),
('sciences', 'Neurosciences', 'neurosciences'),
('sciences', 'Algebre', 'algebre'),
('sciences', 'Robotique', 'robotique'),
('sciences', 'Cryptographie', 'cryptographie'),

('musique', 'Opera', 'opera'),
('musique', 'House', 'house'),
('musique', 'Drill', 'drill'),
('musique', 'Afrobeat', 'afrobeat'),
('musique', 'Kpop', 'kpop'),

('fruits', 'Mandarine', 'mandarine'),
('fruits', 'Pamplemousse', 'pamplemousse'),
('fruits', 'Noix de coco', 'noix de coco'),
('fruits', 'Litchi', 'litchi'),
('fruits', 'Datte', 'datte'),


('pays', 'Etats Unis', 'etats unis'),
('pays', 'Royaume Uni', 'royaume uni'),
('pays', 'Pays Bas', 'pays bas'),
('pays', 'Coree du Sud', 'coree du sud'),
('pays', 'Afrique du Sud', 'afrique du sud'),

('legumes', 'Artichaut', 'artichaut'),
('legumes', 'Asperge', 'asperge'),
('legumes', 'Betterave', 'betterave'),
('legumes', 'Courge', 'courge'),
('legumes', 'Fenouil', 'fenouil'),

('couleurs', 'Bordeaux', 'bordeaux'),
('couleurs', 'Saumon', 'saumon'),
('couleurs', 'Kaki', 'kaki'),
('couleurs', 'Ambre', 'ambre'),
('couleurs', 'Ivoire', 'ivoire'),

('sports', 'Baseball', 'baseball'),
('sports', 'Hockey', 'hockey'),
('sports', 'Petanque', 'petanque'),
('sports', 'Gymnastique', 'gymnastique'),
('sports', 'Marathon', 'marathon'),

('metiers', 'Comptable', 'comptable'),
('metiers', 'Banquier', 'banquier'),
('metiers', 'Notaire', 'notaire'),
('metiers', 'Electricien', 'electricien'),
('metiers', 'Menuisier', 'menuisier'),

('capitales', 'Londres', 'londres'),
('capitales', 'Washington', 'washington'),
('capitales', 'Amsterdam', 'amsterdam'),
('capitales', 'Athenes', 'athenes'),
('capitales', 'Dublin', 'dublin'),

('instruments', 'Harmonica', 'harmonica'),
('instruments', 'Clavecin', 'clavecin'),
('instruments', 'Didgeridoo', 'didgeridoo'),
('instruments', 'Synthetiseur', 'synthetiseur'),
('instruments', 'Djembe', 'djembe'),

('vehicules', 'Monospace', 'monospace'),
('vehicules', 'Pickup', 'pickup'),
('vehicules', 'Motoneige', 'motoneige'),
('vehicules', 'Voilier', 'voilier'),
('vehicules', 'Fusee', 'fusee'),



('vetements', 'Cardigan', 'cardigan'),
('vetements', 'Sweat', 'sweat'),
('vetements', 'Cravate', 'cravate'),
('vetements', 'Maillot', 'maillot'),
('vetements', 'Baskets', 'baskets'),

('desserts', 'Crumble', 'crumble'),
('desserts', 'Madeleine', 'madeleine'),
('desserts', 'Fondant', 'fondant'),
('desserts', 'Beignet', 'beignet'),
('desserts', 'Tarte tatin', 'tarte tatin'),



('jeux_video', 'League of Legends', 'league of legends'),
('jeux_video', 'Counter Strike', 'counter strike'),
('jeux_video', 'GTA', 'gta'),
('jeux_video', 'Apex Legends', 'apex legends'),
('jeux_video', 'Elden Ring', 'elden ring'),

('sciences', 'Thermodynamique', 'thermodynamique'),
('sciences', 'Astrophysique', 'astrophysique'),
('sciences', 'Biochimie', 'biochimie'),
('sciences', 'Epidemiologie', 'epidemiologie'),
('sciences', 'Nanotechnologie', 'nanotechnologie'),

('musique', 'Rnb', 'rnb'),
('musique', 'Trap', 'trap'),
('musique', 'Folk', 'folk'),
('musique', 'Grunge', 'grunge'),
('musique', 'Flamenco', 'flamenco'),

('fruits', 'Clementine', 'clementine'),
('fruits', 'Goyave', 'goyave'),
('fruits', 'Papaye', 'papaye'),


('pays', 'Russie', 'russie'),
('pays', 'Ukraine', 'ukraine'),
('pays', 'Turquie', 'turquie'),
('pays', 'Grece', 'grece'),
('pays', 'Autriche', 'autriche'),
('pays', 'Irlande', 'irlande'),

('legumes', 'Salade', 'salade'),
('legumes', 'Chou fleur', 'chou fleur'),
('legumes', 'Haricot vert', 'haricot vert'),

('couleurs', 'Bleu marine', 'bleu marine'),
('couleurs', 'Fuchsia', 'fuchsia'),

('sports', 'Ping pong', 'ping pong'),
('sports', 'Halterophilie', 'halterophilie'),

('metiers', 'Psychologue', 'psychologue'),

('capitales', 'Moscou', 'moscou'),

('instruments', 'Triangle', 'triangle'),

('vehicules', 'Sous marin', 'sous marin'),

('vetements', 'Casquette', 'casquette'),

('boissons', 'Sodas', 'sodas'),
('boissons', 'Heineken', 'heineken'),
('boissons', 'Nespresso', 'nespresso'),
('boissons', 'Desperados', 'desperados'),
('boissons', 'Ice tea', 'ice tea'),
('boissons', 'Fuze Tea', 'fuze tea'),
('boissons', 'Nestea', 'nestea'),
('boissons', 'Arizona', 'arizona'),
('boissons', 'Minute Maid', 'minute maid'),
('boissons', 'Granini', 'granini'),
('boissons', 'Joker', 'joker'),
('boissons', 'Pago', 'pago'),
('boissons', 'Innocent', 'innocent'),
('boissons', 'Pressade', 'pressade'),
('boissons', 'Jus ananas', 'jus ananas'),
('boissons', 'Jus raisin', 'jus raisin'),
('boissons', 'Jus tomate', 'jus tomate'),
('boissons', 'Jus mangue', 'jus mangue'),
('boissons', 'Jus multifruits', 'jus multifruits'),
('boissons', 'Nectar', 'nectar'),



('jeux_video', 'Call of Duty', 'call of duty'),
('jeux_video', 'Assassins Creed', 'assassins creed'),
('jeux_video', 'World of Warcraft', 'world of warcraft'),

('sciences', 'IA', 'ia'),
('sciences', 'Quantique', 'quantique'),
('sciences', 'Machine learning', 'machine learning'),

('musique', 'Hip hop', 'hip hop'),
('musique', 'Hiphop', 'hiphop'),
('musique', 'Lo fi', 'lo fi'),

('fruits', 'Nectarine', 'nectarine'),
('fruits', 'Mirabelle', 'mirabelle'),
('fruits', 'Mure', 'mure'),
('fruits', 'Cassis', 'cassis'),
('fruits', 'Groseille', 'groseille'),
('fruits', 'Pamplemousse rose', 'pamplemousse rose'),
('fruits', 'Citron vert', 'citron vert'),
('fruits', 'Fruit de la passion', 'fruit de la passion'),
('fruits', 'Kaki', 'kaki'),
('fruits', 'Cranberry', 'cranberry'),
('fruits', 'Cassis noir', 'cassis noir'),
('fruits', 'Pruneau', 'pruneau'),
('fruits', 'Coing', 'coing'),
('fruits', 'Carambole', 'carambole'),
('fruits', 'Kumquat', 'kumquat'),
('fruits', 'Pomelo', 'pomelo'),
('fruits', 'Grenadille', 'grenadille'),
('fruits', 'Baie de goji', 'baie de goji'),
('fruits', 'Mangoustan', 'mangoustan'),
('fruits', 'Cacao', 'cacao'),
('fruits', 'Tangerine', 'tangerine'),
('fruits', 'Yuzu', 'yuzu'),
('fruits', 'Bergamote', 'bergamote'),
('fruits', 'Cedrat', 'cedrat'),
('fruits', 'Banane plantain', 'banane plantain'),
('fruits', 'Airelle', 'airelle'),
('fruits', 'Canneberge', 'canneberge'),
('fruits', 'Physalis', 'physalis'),
('fruits', 'Mure sauvage', 'mure sauvage'),
('fruits', 'Baie d argousier', 'baie d argousier'),
('fruits', 'Baie de sureau', 'baie de sureau'),
('fruits', 'Baie de genevre', 'baie de genevre'),
('fruits', 'Melon charentais', 'melon charentais'),
('fruits', 'Melon jaune', 'melon jaune'),
('fruits', 'Fruit du dragon', 'fruit du dragon'),
('fruits', 'Pitaya', 'pitaya'),
('fruits', 'Ramboutan', 'ramboutan'),
('fruits', 'Longane', 'longane'),
('fruits', 'Durian', 'durian'),
('fruits', 'Salak', 'salak'),
('fruits', 'Jacquier', 'jacquier'),
('fruits', 'Corossol', 'corossol'),
('fruits', 'Sapotille', 'sapotille'),
('fruits', 'Feijoa', 'feijoa'),
('fruits', 'Nashi', 'nashi'),
('fruits', 'Jujube', 'jujube'),
('fruits', 'Arbouse', 'arbouse'),
('fruits', 'Cynorrhodon', 'cynorrhodon'),
('fruits', 'Nefle', 'nefle'),
('fruits', 'Nefle du Japon', 'nefle du japon'),
('fruits', 'Asimine', 'asimine'),
('fruits', 'Tamarin', 'tamarin'),
('fruits', 'Quetsche', 'quetsche'),
('fruits', 'Reine claude', 'reine claude'),
('fruits', 'Prunelle', 'prunelle'),
('fruits', 'Baie d aronia', 'baie d aronia'),
('fruits', 'Olive', 'olive'),
('fruits', 'Avocat', 'avocat'),
('fruits', 'Rhubarbe', 'rhubarbe'),
('fruits', 'Figue de barbarie', 'figue de barbarie'),
('fruits', 'Noix', 'noix'),
('fruits', 'Amande', 'amande'),
('fruits', 'Noisette', 'noisette'),
('fruits', 'Pistache', 'pistache'),
('fruits', 'Pacane', 'pacane'),
('fruits', 'Macadamia', 'macadamia'),
('fruits', 'Pecan', 'pecan'),
('fruits', 'Noix du Bresil', 'noix du bresil'),


('pays', 'Danemark', 'danemark'),
('pays', 'Islande', 'islande'),
('pays', 'Pologne', 'pologne'),
('pays', 'Hongrie', 'hongrie'),
('pays', 'Roumanie', 'roumanie'),
('pays', 'Bulgarie', 'bulgarie'),
('pays', 'Croatie', 'croatie'),
('pays', 'Serbie', 'serbie'),
('pays', 'Algerie', 'algerie'),
('pays', 'Tunisie', 'tunisie'),
('pays', 'Nigeria', 'nigeria'),
('pays', 'Kenya', 'kenya'),
('pays', 'Senegal', 'senegal'),
('pays', 'Perou', 'perou'),
('pays', 'Chili', 'chili'),
('pays', 'Colombie', 'colombie'),
('pays', 'Thailande', 'thailande'),
('pays', 'Vietnam', 'vietnam'),
('pays', 'Indonesie', 'indonesie'),
('pays', 'Nouvelle Zelande', 'nouvelle zelande'),

('legumes', 'Potiron', 'potiron'),
('legumes', 'Potimarron', 'potimarron'),
('legumes', 'Butternut', 'butternut'),
('legumes', 'Endive', 'endive'),
('legumes', 'Blette', 'blette'),
('legumes', 'Chou rouge', 'chou rouge'),
('legumes', 'Chou vert', 'chou vert'),
('legumes', 'Pois chiche', 'pois chiche'),
('legumes', 'Lentille', 'lentille'),
('legumes', 'Mais', 'mais'),
('legumes', 'Topinambour', 'topinambour'),
('legumes', 'Rutabaga', 'rutabaga'),
('legumes', 'Salsifis', 'salsifis'),
('legumes', 'Pois mange tout', 'pois mange tout'),
('legumes', 'Panais', 'panais'),
('legumes', 'Cresson', 'cresson'),
('legumes', 'Roquette', 'roquette'),
('legumes', 'Avocat', 'avocat'),
('legumes', 'Manioc', 'manioc'),
('legumes', 'Pois casses', 'pois casses'),

('couleurs', 'Turquin', 'turquin'),
('couleurs', 'Olive', 'olive'),
('couleurs', 'Corail', 'corail'),
('couleurs', 'Brique', 'brique'),
('couleurs', 'Moutarde', 'moutarde'),
('couleurs', 'Menthe', 'menthe'),
('couleurs', 'Prune', 'prune'),
('couleurs', 'Aubergine', 'aubergine'),
('couleurs', 'Taupe', 'taupe'),
('couleurs', 'Sable', 'sable'),
('couleurs', 'Caramel', 'caramel'),
('couleurs', 'Chocolat', 'chocolat'),
('couleurs', 'Cuivre', 'cuivre'),
('couleurs', 'Bronze', 'bronze'),
('couleurs', 'Perle', 'perle'),
('couleurs', 'Emeraude', 'emeraude'),
('couleurs', 'Rubis', 'rubis'),
('couleurs', 'Saphir', 'saphir'),
('couleurs', 'Lilas', 'lilas'),
('couleurs', 'Anthracite', 'anthracite'),
('couleurs', 'Azur', 'azur'),
('couleurs', 'Aigue marine', 'aigue marine'),
('couleurs', 'Aquamarine', 'aquamarine'),
('couleurs', 'Ardoise', 'ardoise'),
('couleurs', 'Bistre', 'bistre'),
('couleurs', 'Blond', 'blond'),
('couleurs', 'Bouton d or', 'bouton d or'),
('couleurs', 'Cacao', 'cacao'),
('couleurs', 'Canari', 'canari'),
('couleurs', 'Cendre', 'cendre'),
('couleurs', 'Cerise', 'cerise'),
('couleurs', 'Chartreuse', 'chartreuse'),
('couleurs', 'Chataigne', 'chataigne'),
('couleurs', 'Citron', 'citron'),
('couleurs', 'Cobalt', 'cobalt'),
('couleurs', 'Coquelicot', 'coquelicot'),
('couleurs', 'Crimson', 'crimson'),
('couleurs', 'Creme', 'creme'),
('couleurs', 'Ebene', 'ebene'),
('couleurs', 'Ecru', 'ecru'),
('couleurs', 'Ecarlate', 'ecarlate'),
('couleurs', 'Encre', 'encre'),
('couleurs', 'Fauve', 'fauve'),
('couleurs', 'Flamme', 'flamme'),
('couleurs', 'Framboise', 'framboise'),
('couleurs', 'Fraise', 'fraise'),
('couleurs', 'Garance', 'garance'),
('couleurs', 'Glacier', 'glacier'),
('couleurs', 'Grenat', 'grenat'),
('couleurs', 'Grège', 'grege'),
('couleurs', 'Groseille', 'groseille'),
('couleurs', 'Havane', 'havane'),
('couleurs', 'Isabelle', 'isabelle'),
('couleurs', 'Jade', 'jade'),
('couleurs', 'Jonquille', 'jonquille'),
('couleurs', 'Lagon', 'lagon'),
('couleurs', 'Lierre', 'lierre'),
('couleurs', 'Lin', 'lin'),
('couleurs', 'Mandarine', 'mandarine'),
('couleurs', 'Mauve', 'mauve'),
('couleurs', 'Miel', 'miel'),
('couleurs', 'Mocha', 'mocha'),
('couleurs', 'Nacre', 'nacre'),
('couleurs', 'Navy', 'navy'),
('couleurs', 'Noisette', 'noisette'),
('couleurs', 'Occre jaune', 'occre jaune'),
('couleurs', 'Opaline', 'opaline'),
('couleurs', 'Orchidee', 'orchidee'),
('couleurs', 'Orpiment', 'orpiment'),
('couleurs', 'Paille', 'paille'),
('couleurs', 'Papaye', 'papaye'),
('couleurs', 'Pervenche', 'pervenche'),
('couleurs', 'Pistache', 'pistache'),
('couleurs', 'Platinium', 'platinium'),
('couleurs', 'Pourpre', 'pourpre'),
('couleurs', 'Poussin', 'poussin'),
('couleurs', 'Roux', 'roux'),
('couleurs', 'Sang de boeuf', 'sang de boeuf'),
('couleurs', 'Sepia', 'sepia'),
('couleurs', 'Topaze', 'topaze'),
('couleurs', 'Vanille', 'vanille'),
('couleurs', 'Vermeil', 'vermeil'),
('couleurs', 'Veronese', 'veronese'),
('couleurs', 'Vieil or', 'vieil or'),
('couleurs', 'Zinzolin', 'zinzolin'),
('couleurs', 'Bleu ciel', 'bleu ciel'),
('couleurs', 'Bleu roi', 'bleu roi'),
('couleurs', 'Bleu nuit', 'bleu nuit'),
('couleurs', 'Bleu canard', 'bleu canard'),
('couleurs', 'Bleu petrole', 'bleu petrole'),
('couleurs', 'Vert anis', 'vert anis'),
('couleurs', 'Vert pomme', 'vert pomme'),
('couleurs', 'Vert sapin', 'vert sapin'),
('couleurs', 'Vert bouteille', 'vert bouteille'),
('couleurs', 'Vert d eau', 'vert d eau'),
('couleurs', 'Vert kaki', 'vert kaki'),
('couleurs', 'Jaune citron', 'jaune citron'),
('couleurs', 'Jaune paille', 'jaune paille'),
('couleurs', 'Jaune d or', 'jaune d or'),
('couleurs', 'Orange sanguine', 'orange sanguine'),
('couleurs', 'Orange brule', 'orange brule'),
('couleurs', 'Rouge carmin', 'rouge carmin'),
('couleurs', 'Rouge cerise', 'rouge cerise'),
('couleurs', 'Rouge brique', 'rouge brique'),
('couleurs', 'Rouge vermillon', 'rouge vermillon'),
('couleurs', 'Rouge grenat', 'rouge grenat'),
('couleurs', 'Rose pale', 'rose pale'),
('couleurs', 'Rose bonbon', 'rose bonbon'),
('couleurs', 'Rose poudre', 'rose poudre'),
('couleurs', 'Rose saumon', 'rose saumon'),
('couleurs', 'Violet prune', 'violet prune'),
('couleurs', 'Violet amethyste', 'violet amethyste'),
('couleurs', 'Violet imperial', 'violet imperial'),
('couleurs', 'Gris souris', 'gris souris'),
('couleurs', 'Gris perle', 'gris perle'),
('couleurs', 'Gris clair', 'gris clair'),
('couleurs', 'Gris fonce', 'gris fonce'),
('couleurs', 'Blanc casse', 'blanc casse'),
('couleurs', 'Blanc ivoire', 'blanc ivoire'),
('couleurs', 'Blanc neige', 'blanc neige'),
('couleurs', 'Noir corbeau', 'noir corbeau'),
('couleurs', 'Noir jais', 'noir jais'),
('couleurs', 'Marron glace', 'marron glace'),
('couleurs', 'Marron chocolat', 'marron chocolat'),
('couleurs', 'Marron noisette', 'marron noisette'),

('sports', 'Taekwondo', 'taekwondo'),
('sports', 'Aviron', 'aviron'),
('sports', 'Voile', 'voile'),
('sports', 'Plongee', 'plongee'),
('sports', 'Canoe kayak', 'canoe kayak'),
('sports', 'Lutte', 'lutte'),
('sports', 'BMX', 'bmx'),
('sports', 'Skateboard', 'skateboard'),
('sports', 'Snowboard', 'snowboard'),
('sports', 'Biathlon', 'biathlon'),
('sports', 'Curling', 'curling'),
('sports', 'Squash', 'squash'),
('sports', 'Padel', 'padel'),
('sports', 'Water polo', 'water polo'),
('sports', 'Lancer de javelot', 'lancer de javelot'),
('sports', 'Decathlon', 'decathlon'),
('sports', 'Course a pied', 'course a pied'),
('sports', 'Equitation', 'equitation'),
('sports', 'Tir a l arc', 'tir a l arc'),
('sports', 'MMA', 'mma'),

('metiers', 'Boucher', 'boucher'),
('metiers', 'Patissier', 'patissier'),
('metiers', 'Serveur', 'serveur'),
('metiers', 'Receptionniste', 'receptionniste'),
('metiers', 'Agriculteur', 'agriculteur'),
('metiers', 'Maraicher', 'maraicher'),
('metiers', 'Bricoleur', 'bricoleur'),
('metiers', 'Soudeur', 'soudeur'),
('metiers', 'Carreleur', 'carreleur'),
('metiers', 'Macon', 'macon'),
('metiers', 'Conducteur', 'conducteur'),
('metiers', 'Pilote', 'pilote'),
('metiers', 'Hotesse de l air', 'hotesse de l air'),
('metiers', 'Traducteur', 'traducteur'),
('metiers', 'Bibliothecaire', 'bibliothecaire'),
('metiers', 'Chercheur', 'chercheur'),
('metiers', 'Photographe', 'photographe'),
('metiers', 'Designer', 'designer'),
('metiers', 'Community manager', 'community manager'),
('metiers', 'Caissier', 'caissier'),

('capitales', 'Copenhague', 'copenhague'),
('capitales', 'Reykjavik', 'reykjavik'),
('capitales', 'Varsovie', 'varsovie'),
('capitales', 'Budapest', 'budapest'),
('capitales', 'Bucarest', 'bucarest'),
('capitales', 'Sofia', 'sofia'),
('capitales', 'Zagreb', 'zagreb'),
('capitales', 'Belgrade', 'belgrade'),
('capitales', 'Alger', 'alger'),
('capitales', 'Tunis', 'tunis'),
('capitales', 'Abuja', 'abuja'),
('capitales', 'Nairobi', 'nairobi'),
('capitales', 'Dakar', 'dakar'),
('capitales', 'Lima', 'lima'),
('capitales', 'Santiago', 'santiago'),
('capitales', 'Bogota', 'bogota'),
('capitales', 'Bangkok', 'bangkok'),
('capitales', 'Hanoi', 'hanoi'),
('capitales', 'Jakarta', 'jakarta'),
('capitales', 'Kaboul', 'kaboul'),
('capitales', 'Pretoria', 'pretoria'),
('capitales', 'Tirane', 'tirane'),
('capitales', 'Andorre la Vieille', 'andorre la vieille'),
('capitales', 'Luanda', 'luanda'),
('capitales', 'Saint Johns', 'saint johns'),
('capitales', 'Erevan', 'erevan'),
('capitales', 'Vienne', 'vienne'),
('capitales', 'Bakou', 'bakou'),
('capitales', 'Nassau', 'nassau'),
('capitales', 'Manama', 'manama'),
('capitales', 'Dacca', 'dacca'),
('capitales', 'Bridgetown', 'bridgetown'),
('capitales', 'Minsk', 'minsk'),
('capitales', 'Belmopan', 'belmopan'),
('capitales', 'Porto Novo', 'porto novo'),
('capitales', 'Thimphou', 'thimphou'),
('capitales', 'La Paz', 'la paz'),
('capitales', 'Sucre', 'sucre'),
('capitales', 'Sarajevo', 'sarajevo'),
('capitales', 'Gaborone', 'gaborone'),
('capitales', 'Bandar Seri Begawan', 'bandar seri begawan'),
('capitales', 'Ouagadougou', 'ouagadougou'),
('capitales', 'Gitega', 'gitega'),
('capitales', 'Phnom Penh', 'phnom penh'),
('capitales', 'Yaounde', 'yaounde'),
('capitales', 'Praia', 'praia'),
('capitales', 'Bangui', 'bangui'),
('capitales', 'Ndjamena', 'ndjamena'),
('capitales', 'Moroni', 'moroni'),
('capitales', 'Brazzaville', 'brazzaville'),
('capitales', 'Kinshasa', 'kinshasa'),
('capitales', 'San Jose', 'san jose'),
('capitales', 'Yamoussoukro', 'yamoussoukro'),
('capitales', 'Nicosie', 'nicosie'),
('capitales', 'Prague', 'prague'),
('capitales', 'Djibouti', 'djibouti'),
('capitales', 'Roseau', 'roseau'),
('capitales', 'Saint Domingue', 'saint domingue'),
('capitales', 'Quito', 'quito'),
('capitales', 'San Salvador', 'san salvador'),
('capitales', 'Malabo', 'malabo'),
('capitales', 'Asmara', 'asmara'),
('capitales', 'Tallinn', 'tallinn'),
('capitales', 'Mbabane', 'mbabane'),
('capitales', 'Addis Abeba', 'addis abeba'),
('capitales', 'Suva', 'suva'),
('capitales', 'Libreville', 'libreville'),
('capitales', 'Banjul', 'banjul'),
('capitales', 'Tbilissi', 'tbilissi'),
('capitales', 'Accra', 'accra'),
('capitales', 'Saint Georges', 'saint georges'),
('capitales', 'Guatemala', 'guatemala'),
('capitales', 'Conakry', 'conakry'),
('capitales', 'Bissau', 'bissau'),
('capitales', 'Georgetown', 'georgetown'),
('capitales', 'Port au Prince', 'port au prince'),
('capitales', 'Tegucigalpa', 'tegucigalpa'),
('capitales', 'New Delhi', 'new delhi'),
('capitales', 'Teheran', 'teheran'),
('capitales', 'Bagdad', 'bagdad'),
('capitales', 'Jerusalem', 'jerusalem'),
('capitales', 'Amman', 'amman'),
('capitales', 'Astana', 'astana'),
('capitales', 'Noursoultan', 'noursoultan'),
('capitales', 'Tarawa Sud', 'tarawa sud'),
('capitales', 'Pristina', 'pristina'),
('capitales', 'Koweit', 'koweit'),
('capitales', 'Bichkek', 'bichkek'),
('capitales', 'Vientiane', 'vientiane'),
('capitales', 'Riga', 'riga'),
('capitales', 'Beyrouth', 'beyrouth'),
('capitales', 'Maseru', 'maseru'),
('capitales', 'Monrovia', 'monrovia'),
('capitales', 'Tripoli', 'tripoli'),
('capitales', 'Vaduz', 'vaduz'),
('capitales', 'Vilnius', 'vilnius'),
('capitales', 'Luxembourg', 'luxembourg'),
('capitales', 'Antananarivo', 'antananarivo'),
('capitales', 'Lilongwe', 'lilongwe'),
('capitales', 'Kuala Lumpur', 'kuala lumpur'),
('capitales', 'Male', 'male'),
('capitales', 'Bamako', 'bamako'),
('capitales', 'La Valette', 'la valette'),
('capitales', 'Majuro', 'majuro'),
('capitales', 'Nouakchott', 'nouakchott'),
('capitales', 'Port Louis', 'port louis'),
('capitales', 'Palikir', 'palikir'),
('capitales', 'Chisinau', 'chisinau'),
('capitales', 'Monaco', 'monaco'),
('capitales', 'Oulan Bator', 'oulan bator'),
('capitales', 'Podgorica', 'podgorica'),
('capitales', 'Maputo', 'maputo'),
('capitales', 'Naypyidaw', 'naypyidaw'),
('capitales', 'Windhoek', 'windhoek'),
('capitales', 'Yaren', 'yaren'),
('capitales', 'Katmandou', 'katmandou'),
('capitales', 'Managua', 'managua'),
('capitales', 'Niamey', 'niamey'),
('capitales', 'Pyongyang', 'pyongyang'),
('capitales', 'Skopje', 'skopje'),
('capitales', 'Mascate', 'mascate'),
('capitales', 'Islamabad', 'islamabad'),
('capitales', 'Ngerulmud', 'ngerulmud'),
('capitales', 'Panama', 'panama'),
('capitales', 'Port Moresby', 'port moresby'),
('capitales', 'Asuncion', 'asuncion'),
('capitales', 'Manille', 'manille'),
('capitales', 'Doha', 'doha'),
('capitales', 'Kigali', 'kigali'),
('capitales', 'Basseterre', 'basseterre'),
('capitales', 'Castries', 'castries'),
('capitales', 'Kingstown', 'kingstown'),
('capitales', 'Apia', 'apia'),
('capitales', 'Saint Marin', 'saint marin'),
('capitales', 'Sao Tome', 'sao tome'),
('capitales', 'Riyad', 'riyad'),
('capitales', 'Freetown', 'freetown'),
('capitales', 'Singapour', 'singapour'),
('capitales', 'Bratislava', 'bratislava'),
('capitales', 'Ljubljana', 'ljubljana'),
('capitales', 'Honiara', 'honiara'),
('capitales', 'Mogadiscio', 'mogadiscio'),
('capitales', 'Juba', 'juba'),
('capitales', 'Sri Jayawardenepura Kotte', 'sri jayawardenepura kotte'),
('capitales', 'Khartoum', 'khartoum'),
('capitales', 'Paramaribo', 'paramaribo'),
('capitales', 'Berne', 'berne'),
('capitales', 'Damas', 'damas'),
('capitales', 'Douchanbe', 'douchanbe'),
('capitales', 'Dodoma', 'dodoma'),
('capitales', 'Lome', 'lome'),
('capitales', 'Nukualofa', 'nukualofa'),
('capitales', 'Port of Spain', 'port of spain'),
('capitales', 'Ankara', 'ankara'),
('capitales', 'Achgabat', 'achgabat'),
('capitales', 'Funafuti', 'funafuti'),
('capitales', 'Kampala', 'kampala'),
('capitales', 'Kiev', 'kiev'),
('capitales', 'Abou Dabi', 'abou dabi'),
('capitales', 'Montevideo', 'montevideo'),
('capitales', 'Tachkent', 'tachkent'),
('capitales', 'Port Vila', 'port vila'),
('capitales', 'Vatican', 'vatican'),
('capitales', 'Caracas', 'caracas'),
('capitales', 'Sanaa', 'sanaa'),
('capitales', 'Lusaka', 'lusaka'),
('capitales', 'Harare', 'harare'),

('instruments', 'Viola', 'viola'),
('instruments', 'Piccolo', 'piccolo'),
('instruments', 'Tuba', 'tuba'),
('instruments', 'Ocarina', 'ocarina'),
('instruments', 'Castagnettes', 'castagnettes'),
('instruments', 'Conga', 'conga'),
('instruments', 'Bongo', 'bongo'),
('instruments', 'Maracas', 'maracas'),
('instruments', 'Gong', 'gong'),
('instruments', 'Cymbales', 'cymbales'),
('instruments', 'Kalimba', 'kalimba'),
('instruments', 'Balalaika', 'balalaika'),
('instruments', 'Luth', 'luth'),
('instruments', 'Vibraphone', 'vibraphone'),
('instruments', 'Mellophone', 'mellophone'),
('instruments', 'Cor', 'cor'),
('instruments', 'Cajon', 'cajon'),
('instruments', 'Melodica', 'melodica'),
('instruments', 'Flute traversiere', 'flute traversiere'),
('instruments', 'Orgue', 'orgue'),

('vehicules', 'Berline', 'berline'),
('vehicules', 'Cabriolet', 'cabriolet'),
('vehicules', 'SUV', 'suv'),
('vehicules', 'Camping car', 'camping car'),
('vehicules', 'Minibus', 'minibus'),
('vehicules', 'TGV', 'tgv'),
('vehicules', 'Jet ski', 'jet ski'),
('vehicules', 'Yacht', 'yacht'),
('vehicules', 'Peniche', 'peniche'),
('vehicules', 'Montgolfiere', 'montgolfiere'),
('vehicules', 'Deltaplane', 'deltaplane'),
('vehicules', 'ULM', 'ulm'),
('vehicules', 'Chariot', 'chariot'),
('vehicules', 'Quad', 'quad'),
('vehicules', 'Buggy', 'buggy'),
('vehicules', 'Kart', 'kart'),
('vehicules', 'Ambulance', 'ambulance'),
('vehicules', 'Depanneuse', 'depanneuse'),
('vehicules', 'Bulldozer', 'bulldozer'),
('vehicules', 'Pelleteuse', 'pelleteuse'),



('vetements', 'Debardeur', 'debardeur'),
('vetements', 'Polo', 'polo'),
('vetements', 'Doudoune', 'doudoune'),
('vetements', 'Kway', 'kway'),
('vetements', 'Anorak', 'anorak'),
('vetements', 'Combinaison', 'combinaison'),
('vetements', 'Salopette', 'salopette'),
('vetements', 'Legging', 'legging'),
('vetements', 'Collant', 'collant'),
('vetements', 'Pantoufles', 'pantoufles'),
('vetements', 'Mocassins', 'mocassins'),
('vetements', 'Bottes', 'bottes'),
('vetements', 'Espadrilles', 'espadrilles'),
('vetements', 'Moufles', 'moufles'),
('vetements', 'Sous pull', 'sous pull'),
('vetements', 'Brassiere', 'brassiere'),
('vetements', 'Poncho', 'poncho'),
('vetements', 'Kimono', 'kimono'),
('vetements', 'Peignoir', 'peignoir'),
('vetements', 'Costume', 'costume'),

('boissons', 'The glace', 'the glace'),
('boissons', 'Jus citron', 'jus citron'),
('boissons', 'Jus peche', 'jus peche'),
('boissons', 'Jus poire', 'jus poire'),
('boissons', 'Jus fraise', 'jus fraise'),
('boissons', 'Jus abricot', 'jus abricot'),
('boissons', 'Jus pamplemousse', 'jus pamplemousse'),
('boissons', 'Jus cerise', 'jus cerise'),
('boissons', 'Diabolo grenadine', 'diabolo grenadine'),
('boissons', 'Diabolo menthe', 'diabolo menthe'),
('boissons', 'Frappe', 'frappe'),
('boissons', 'Latte', 'latte'),
('boissons', 'Espresso', 'espresso'),
('boissons', 'Moka', 'moka'),
('boissons', 'Macchiato', 'macchiato'),
('boissons', 'Ricore', 'ricore'),
('boissons', 'Seven Up', 'seven up'),
('boissons', 'Dr Pepper', 'dr pepper'),
('boissons', 'Canada Dry', 'canada dry'),
('boissons', 'Cristaline', 'cristaline'),

('desserts', 'Paris brest', 'paris brest'),
('desserts', 'Chouquette', 'chouquette'),
('desserts', 'Religieuse', 'religieuse'),
('desserts', 'Tarte au citron', 'tarte au citron'),
('desserts', 'Tarte aux pommes', 'tarte aux pommes'),
('desserts', 'Foret noire', 'foret noire'),
('desserts', 'Baba au rhum', 'baba au rhum'),
('desserts', 'Creme brulee', 'creme brulee'),
('desserts', 'Ile flottante', 'ile flottante'),
('desserts', 'Riz au lait', 'riz au lait'),
('desserts', 'Compote', 'compote'),
('desserts', 'Pain perdu', 'pain perdu'),
('desserts', 'Charlotte', 'charlotte'),
('desserts', 'Mochi', 'mochi'),
('desserts', 'Canneles', 'canneles'),
('desserts', 'Sundae', 'sundae'),
('desserts', 'Muffin', 'muffin'),
('desserts', 'Cupcake', 'cupcake'),
('desserts', 'Pecan pie', 'pecan pie'),
('desserts', 'Baklava', 'baklava'),



('jeux_video', 'Roblox', 'roblox'),
('jeux_video', 'Rocket League', 'rocket league'),
('jeux_video', 'Among Us', 'among us'),
('jeux_video', 'Terraria', 'terraria'),
('jeux_video', 'Stardew Valley', 'stardew valley'),
('jeux_video', 'Animal Crossing', 'animal crossing'),
('jeux_video', 'Splatoon', 'splatoon'),
('jeux_video', 'Resident Evil', 'resident evil'),
('jeux_video', 'Silent Hill', 'silent hill'),
('jeux_video', 'God of War', 'god of war'),
('jeux_video', 'The Witcher', 'the witcher'),
('jeux_video', 'Fall Guys', 'fall guys'),
('jeux_video', 'Diablo', 'diablo'),
('jeux_video', 'Starcraft', 'starcraft'),
('jeux_video', 'The Sims', 'the sims'),
('jeux_video', 'Monopoly Go', 'monopoly go'),
('jeux_video', 'Brawl Stars', 'brawl stars'),
('jeux_video', 'Clash Royale', 'clash royale'),
('jeux_video', 'Clash of Clans', 'clash of clans'),
('jeux_video', 'Tekken', 'tekken'),

('sciences', 'Calcul', 'calcul'),
('sciences', 'Geometrie', 'geometrie'),
('sciences', 'Analyse', 'analyse'),
('sciences', 'Probabilites', 'probabilites'),
('sciences', 'Logique', 'logique'),
('sciences', 'Mecanique', 'mecanique'),
('sciences', 'Optique', 'optique'),
('sciences', 'Electronique', 'electronique'),
('sciences', 'Electromagnetisme', 'electromagnetisme'),
('sciences', 'Sismologie', 'sismologie'),
('sciences', 'Volcanologie', 'volcanologie'),
('sciences', 'Paleontologie', 'paleontologie'),
('sciences', 'Virologie', 'virologie'),
('sciences', 'Immunologie', 'immunologie'),
('sciences', 'Parasitologie', 'parasitologie'),
('sciences', 'Agronomie', 'agronomie'),
('sciences', 'Hydrologie', 'hydrologie'),
('sciences', 'Algorithmique', 'algorithmique'),
('sciences', 'Data science', 'data science'),
('sciences', 'Cybernetique', 'cybernetique'),

('musique', 'Dubstep', 'dubstep'),
('musique', 'Hard rock', 'hard rock'),
('musique', 'Punk', 'punk'),
('musique', 'Punk rock', 'punk rock'),
('musique', 'Gospel', 'gospel'),
('musique', 'Bossa nova', 'bossa nova'),
('musique', 'Samba', 'samba'),
('musique', 'RaI', 'rai'),
('musique', 'Variete francaise', 'variete francaise'),
('musique', 'Chanson francaise', 'chanson francaise'),
('musique', 'Electro swing', 'electro swing'),
('musique', 'Trance', 'trance'),
('musique', 'Ambient', 'ambient'),
('musique', 'Indie', 'indie'),
('musique', 'Synthwave', 'synthwave'),
('musique', 'New wave', 'new wave'),
('musique', 'Dancehall', 'dancehall'),
('musique', 'Dance', 'dance'),
('musique', 'Jpop', 'jpop'),
('musique', 'Reggaeton', 'reggaeton')
) AS w(slug, label, normalized_label)
ON c.slug = w.slug;

INSERT INTO daily_categories (date, category_id)
SELECT
CURRENT_DATE,
picked.id
FROM (
SELECT c.id
FROM categories c
WHERE c.active = true
ORDER BY c.slug
OFFSET (SELECT MOD(EXTRACT(EPOCH FROM CURRENT_DATE::timestamp)::bigint / 86400, GREATEST(COUNT(*), 1))::int FROM categories WHERE active = true)
LIMIT 1
) AS picked
ON CONFLICT (date) DO UPDATE
SET category_id = EXCLUDED.category_id;
