DELETE FROM daily_categories;
DELETE FROM category_words;
DELETE FROM categories;

INSERT INTO categories (id, slug, name, difficulty, active)
SELECT
(substr(md5(v.slug), 1, 8) || '-' || substr(md5(v.slug), 9, 4) || '-' || substr(md5(v.slug), 13, 4) || '-' || substr(md5(v.slug), 17, 4) || '-' || substr(md5(v.slug), 21, 12))::uuid,
v.slug,
v.name,
v.difficulty,
v.active
FROM (
VALUES
('fruits', 'Fruits', 1, true),
('animaux', 'Animaux', 1, true),
('pays', 'Pays', 2, true),
('legumes', 'Legumes', 1, true),
('couleurs', 'Couleurs', 1, true),
('sports', 'Sports', 2, true),
('metiers', 'Metiers', 2, true),
('capitales', 'Capitales', 3, true),
('instruments', 'Instruments', 2, true),
('vehicules', 'Vehicules', 1, true),
('fleurs', 'Fleurs', 2, true),
('emotions', 'Emotions', 1, true),
('vetements', 'Vetements', 1, true),
('boissons', 'Boissons', 1, true),
('desserts', 'Desserts', 1, true),
('objets_maison', 'Objets de la maison', 1, true),
('cinema', 'Cinema', 3, true),
('jeux_video', 'Jeux video', 2, true),
('sciences', 'Sciences', 3, true),
('musique', 'Musique', 2, true)
) AS v(slug, name, difficulty, active)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
difficulty = EXCLUDED.difficulty,
active = EXCLUDED.active;

INSERT INTO category_words (id, category_id, label, normalized_label)
SELECT
(substr(md5(c.slug || ':' || w.normalized_label), 1, 8) || '-' || substr(md5(c.slug || ':' || w.normalized_label), 9, 4) || '-' || substr(md5(c.slug || ':' || w.normalized_label), 13, 4) || '-' || substr(md5(c.slug || ':' || w.normalized_label), 17, 4) || '-' || substr(md5(c.slug || ':' || w.normalized_label), 21, 12))::uuid,
c.id,
w.label,
w.normalized_label
FROM categories c
JOIN (
VALUES
('fruits', 'Pomme', 'pomme'),
('fruits', 'Banane', 'banane'),
('fruits', 'Orange', 'orange'),
('fruits', 'Poire', 'poire'),
('fruits', 'Mangue', 'mangue'),
('fruits', 'Fraise', 'fraise'),
('fruits', 'Framboise', 'framboise'),
('fruits', 'Myrtille', 'myrtille'),
('fruits', 'Ananas', 'ananas'),
('fruits', 'Cerise', 'cerise'),
('fruits', 'Abricot', 'abricot'),
('fruits', 'Peche', 'peche'),
('fruits', 'Prune', 'prune'),
('fruits', 'Citron', 'citron'),
('fruits', 'Kiwi', 'kiwi'),

('animaux', 'Chat', 'chat'),
('animaux', 'Chien', 'chien'),
('animaux', 'Lion', 'lion'),
('animaux', 'Tigre', 'tigre'),
('animaux', 'Elephant', 'elephant'),
('animaux', 'Girafe', 'girafe'),
('animaux', 'Zebre', 'zebre'),
('animaux', 'Loup', 'loup'),
('animaux', 'Renard', 'renard'),
('animaux', 'Lapin', 'lapin'),
('animaux', 'Cheval', 'cheval'),
('animaux', 'Vache', 'vache'),
('animaux', 'Ours', 'ours'),
('animaux', 'Panda', 'panda'),
('animaux', 'Dauphin', 'dauphin'),

('pays', 'France', 'france'),
('pays', 'Espagne', 'espagne'),
('pays', 'Italie', 'italie'),
('pays', 'Allemagne', 'allemagne'),
('pays', 'Portugal', 'portugal'),
('pays', 'Belgique', 'belgique'),
('pays', 'Suisse', 'suisse'),
('pays', 'Canada', 'canada'),
('pays', 'Mexique', 'mexique'),
('pays', 'Bresil', 'bresil'),
('pays', 'Argentine', 'argentine'),
('pays', 'Japon', 'japon'),
('pays', 'Inde', 'inde'),
('pays', 'Maroc', 'maroc'),
('pays', 'Egypte', 'egypte'),

('legumes', 'Carotte', 'carotte'),
('legumes', 'Tomate', 'tomate'),
('legumes', 'Courgette', 'courgette'),
('legumes', 'Aubergine', 'aubergine'),
('legumes', 'Poireau', 'poireau'),
('legumes', 'Oignon', 'oignon'),
('legumes', 'Ail', 'ail'),
('legumes', 'Pomme de terre', 'pomme de terre'),
('legumes', 'Poivron', 'poivron'),
('legumes', 'Concombre', 'concombre'),
('legumes', 'Radis', 'radis'),
('legumes', 'Navet', 'navet'),
('legumes', 'Chou', 'chou'),
('legumes', 'Brocoli', 'brocoli'),
('legumes', 'Epinard', 'epinard'),

('couleurs', 'Rouge', 'rouge'),
('couleurs', 'Bleu', 'bleu'),
('couleurs', 'Vert', 'vert'),
('couleurs', 'Jaune', 'jaune'),
('couleurs', 'Orange', 'orange'),
('couleurs', 'Violet', 'violet'),
('couleurs', 'Rose', 'rose'),
('couleurs', 'Marron', 'marron'),
('couleurs', 'Noir', 'noir'),
('couleurs', 'Blanc', 'blanc'),
('couleurs', 'Gris', 'gris'),
('couleurs', 'Turquoise', 'turquoise'),
('couleurs', 'Beige', 'beige'),
('couleurs', 'Doré', 'dore'),
('couleurs', 'Argenté', 'argente'),

('sports', 'Football', 'football'),
('sports', 'Basketball', 'basketball'),
('sports', 'Tennis', 'tennis'),
('sports', 'Rugby', 'rugby'),
('sports', 'Natation', 'natation'),
('sports', 'Cyclisme', 'cyclisme'),
('sports', 'Athletisme', 'athletisme'),
('sports', 'Judo', 'judo'),
('sports', 'Boxe', 'boxe'),
('sports', 'Escalade', 'escalade'),
('sports', 'Golf', 'golf'),
('sports', 'Volleyball', 'volleyball'),
('sports', 'Handball', 'handball'),
('sports', 'Badminton', 'badminton'),
('sports', 'Escrime', 'escrime'),

('metiers', 'Medecin', 'medecin'),
('metiers', 'Infirmier', 'infirmier'),
('metiers', 'Professeur', 'professeur'),
('metiers', 'Boulanger', 'boulanger'),
('metiers', 'Pompier', 'pompier'),
('metiers', 'Policier', 'policier'),
('metiers', 'Avocat', 'avocat'),
('metiers', 'Architecte', 'architecte'),
('metiers', 'Ingenieur', 'ingenieur'),
('metiers', 'Chauffeur', 'chauffeur'),
('metiers', 'Coiffeur', 'coiffeur'),
('metiers', 'Cuisinier', 'cuisinier'),
('metiers', 'Journaliste', 'journaliste'),
('metiers', 'Peintre', 'peintre'),
('metiers', 'Mecanicien', 'mecanicien'),

('capitales', 'Paris', 'paris'),
('capitales', 'Madrid', 'madrid'),
('capitales', 'Rome', 'rome'),
('capitales', 'Berlin', 'berlin'),
('capitales', 'Lisbonne', 'lisbonne'),
('capitales', 'Bruxelles', 'bruxelles'),
('capitales', 'Tokyo', 'tokyo'),
('capitales', 'Ottawa', 'ottawa'),
('capitales', 'Mexico', 'mexico'),
('capitales', 'Brasilia', 'brasilia'),
('capitales', 'Buenos Aires', 'buenos aires'),
('capitales', 'Rabat', 'rabat'),
('capitales', 'Le Caire', 'le caire'),
('capitales', 'Canberra', 'canberra'),
('capitales', 'Seoul', 'seoul'),

('instruments', 'Guitare', 'guitare'),
('instruments', 'Piano', 'piano'),
('instruments', 'Violon', 'violon'),
('instruments', 'Batterie', 'batterie'),
('instruments', 'Flute', 'flute'),
('instruments', 'Trompette', 'trompette'),
('instruments', 'Saxophone', 'saxophone'),
('instruments', 'Harpe', 'harpe'),
('instruments', 'Clarinette', 'clarinette'),
('instruments', 'Accordeon', 'accordeon'),
('instruments', 'Ukulele', 'ukulele'),
('instruments', 'Basse', 'basse'),
('instruments', 'Hautbois', 'hautbois'),
('instruments', 'Trombone', 'trombone'),
('instruments', 'Violoncelle', 'violoncelle'),

('vehicules', 'Voiture', 'voiture'),
('vehicules', 'Moto', 'moto'),
('vehicules', 'Camion', 'camion'),
('vehicules', 'Bus', 'bus'),
('vehicules', 'Train', 'train'),
('vehicules', 'Tramway', 'tramway'),
('vehicules', 'Avion', 'avion'),
('vehicules', 'Helicoptere', 'helicoptere'),
('vehicules', 'Bateau', 'bateau'),
('vehicules', 'Velo', 'velo'),
('vehicules', 'Trottinette', 'trottinette'),
('vehicules', 'Tracteur', 'tracteur'),
('vehicules', 'Fourgon', 'fourgon'),
('vehicules', 'Metro', 'metro'),
('vehicules', 'Navette', 'navette'),

('fleurs', 'Rose', 'rose'),
('fleurs', 'Tulipe', 'tulipe'),
('fleurs', 'Lys', 'lys'),
('fleurs', 'Jasmin', 'jasmin'),
('fleurs', 'Lavande', 'lavande'),
('fleurs', 'Pivoine', 'pivoine'),
('fleurs', 'Marguerite', 'marguerite'),
('fleurs', 'Coquelicot', 'coquelicot'),
('fleurs', 'Orchidee', 'orchidee'),
('fleurs', 'Hortensia', 'hortensia'),
('fleurs', 'Iris', 'iris'),
('fleurs', 'Muguet', 'muguet'),
('fleurs', 'Tournesol', 'tournesol'),
('fleurs', 'Violette', 'violette'),
('fleurs', 'Camelia', 'camelia'),

('emotions', 'Joie', 'joie'),
('emotions', 'Tristesse', 'tristesse'),
('emotions', 'Colere', 'colere'),
('emotions', 'Peur', 'peur'),
('emotions', 'Surprise', 'surprise'),
('emotions', 'Degout', 'degout'),
('emotions', 'Amour', 'amour'),
('emotions', 'Honte', 'honte'),
('emotions', 'Fierte', 'fierte'),
('emotions', 'Stress', 'stress'),
('emotions', 'Calme', 'calme'),
('emotions', 'Anxiete', 'anxiete'),
('emotions', 'Euphorie', 'euphorie'),
('emotions', 'Nostalgie', 'nostalgie'),
('emotions', 'Frustration', 'frustration'),

('vetements', 'Chemise', 'chemise'),
('vetements', 'Tshirt', 'tshirt'),
('vetements', 'Pantalon', 'pantalon'),
('vetements', 'Jean', 'jean'),
('vetements', 'Robe', 'robe'),
('vetements', 'Jupe', 'jupe'),
('vetements', 'Manteau', 'manteau'),
('vetements', 'Veste', 'veste'),
('vetements', 'Pull', 'pull'),
('vetements', 'Echarpe', 'echarpe'),
('vetements', 'Bonnet', 'bonnet'),
('vetements', 'Chapeau', 'chapeau'),
('vetements', 'Chaussures', 'chaussures'),
('vetements', 'Sandales', 'sandales'),
('vetements', 'Ceinture', 'ceinture'),

('boissons', 'Eau', 'eau'),
('boissons', 'Limonade', 'limonade'),
('boissons', 'Jus', 'jus'),
('boissons', 'Cafe', 'cafe'),
('boissons', 'The', 'the'),
('boissons', 'Lait', 'lait'),
('boissons', 'Soda', 'soda'),
('boissons', 'Smoothie', 'smoothie'),
('boissons', 'Sirop', 'sirop'),
('boissons', 'Chocolat chaud', 'chocolat chaud'),
('boissons', 'Milkshake', 'milkshake'),
('boissons', 'Infusion', 'infusion'),
('boissons', 'Lassi', 'lassi'),
('boissons', 'Kefir', 'kefir'),
('boissons', 'Cappuccino', 'cappuccino'),

('desserts', 'Tarte', 'tarte'),
('desserts', 'Gateau', 'gateau'),
('desserts', 'Crepe', 'crepe'),
('desserts', 'Mousse', 'mousse'),
('desserts', 'Glace', 'glace'),
('desserts', 'Sorbet', 'sorbet'),
('desserts', 'Eclair', 'eclair'),
('desserts', 'Macaron', 'macaron'),
('desserts', 'Brownie', 'brownie'),
('desserts', 'Donut', 'donut'),
('desserts', 'Cookie', 'cookie'),
('desserts', 'Flan', 'flan'),
('desserts', 'Tiramisu', 'tiramisu'),
('desserts', 'Panna cotta', 'panna cotta'),
('desserts', 'Gaufre', 'gaufre'),

('objets_maison', 'Table', 'table'),
('objets_maison', 'Chaise', 'chaise'),
('objets_maison', 'Canape', 'canape'),
('objets_maison', 'Lampe', 'lampe'),
('objets_maison', 'Armoire', 'armoire'),
('objets_maison', 'Lit', 'lit'),
('objets_maison', 'Oreiller', 'oreiller'),
('objets_maison', 'Couverture', 'couverture'),
('objets_maison', 'Assiette', 'assiette'),
('objets_maison', 'Verre', 'verre'),
('objets_maison', 'Cuillere', 'cuillere'),
('objets_maison', 'Fourchette', 'fourchette'),
('objets_maison', 'Couteau', 'couteau'),
('objets_maison', 'Casserole', 'casserole'),
('objets_maison', 'Poele', 'poele'),

('cinema', 'Inception', 'inception'),
('cinema', 'Avatar', 'avatar'),
('cinema', 'Titanic', 'titanic'),
('cinema', 'Gladiator', 'gladiator'),
('cinema', 'Interstellar', 'interstellar'),
('cinema', 'Amelie', 'amelie'),
('cinema', 'Parasite', 'parasite'),
('cinema', 'Matrix', 'matrix'),
('cinema', 'Alien', 'alien'),
('cinema', 'Joker', 'joker'),
('cinema', 'Rocky', 'rocky'),
('cinema', 'Coco', 'coco'),
('cinema', 'Up', 'up'),
('cinema', 'Shrek', 'shrek'),
('cinema', 'Dune', 'dune'),

('jeux_video', 'Mario', 'mario'),
('jeux_video', 'Zelda', 'zelda'),
('jeux_video', 'Minecraft', 'minecraft'),
('jeux_video', 'Fortnite', 'fortnite'),
('jeux_video', 'Tetris', 'tetris'),
('jeux_video', 'Pacman', 'pacman'),
('jeux_video', 'Doom', 'doom'),
('jeux_video', 'Fifa', 'fifa'),
('jeux_video', 'Overwatch', 'overwatch'),
('jeux_video', 'Valorant', 'valorant'),
('jeux_video', 'Skyrim', 'skyrim'),
('jeux_video', 'Cyberpunk', 'cyberpunk'),
('jeux_video', 'Pokemon', 'pokemon'),
('jeux_video', 'Sonic', 'sonic'),
('jeux_video', 'Metroid', 'metroid'),

('sciences', 'Physique', 'physique'),
('sciences', 'Chimie', 'chimie'),
('sciences', 'Biologie', 'biologie'),
('sciences', 'Geologie', 'geologie'),
('sciences', 'Astronomie', 'astronomie'),
('sciences', 'Ecologie', 'ecologie'),
('sciences', 'Genetique', 'genetique'),
('sciences', 'Zoologie', 'zoologie'),
('sciences', 'Botanique', 'botanique'),
('sciences', 'Informatique', 'informatique'),
('sciences', 'Statistiques', 'statistiques'),
('sciences', 'Maths', 'maths'),
('sciences', 'Anatomie', 'anatomie'),
('sciences', 'Meteorologie', 'meteorologie'),
('sciences', 'Oceanographie', 'oceanographie'),

('musique', 'Rock', 'rock'),
('musique', 'Jazz', 'jazz'),
('musique', 'Rap', 'rap'),
('musique', 'Pop', 'pop'),
('musique', 'Electro', 'electro'),
('musique', 'Classique', 'classique'),
('musique', 'Reggae', 'reggae'),
('musique', 'Funk', 'funk'),
('musique', 'Soul', 'soul'),
('musique', 'Blues', 'blues'),
('musique', 'Metal', 'metal'),
('musique', 'Techno', 'techno'),
('musique', 'Disco', 'disco'),
('musique', 'Salsa', 'salsa'),
('musique', 'Country', 'country'),

('fruits', 'Raisin', 'raisin'),
('fruits', 'Pasteque', 'pasteque'),
('fruits', 'Melon', 'melon'),
('fruits', 'Grenade', 'grenade'),
('fruits', 'Figue', 'figue'),

('animaux', 'Koala', 'koala'),
('animaux', 'Kangourou', 'kangourou'),
('animaux', 'Tortue', 'tortue'),
('animaux', 'Aigle', 'aigle'),
('animaux', 'Baleine', 'baleine'),

('pays', 'Suede', 'suede'),
('pays', 'Norvege', 'norvege'),
('pays', 'Finlande', 'finlande'),
('pays', 'Chine', 'chine'),
('pays', 'Australie', 'australie'),

('legumes', 'Haricot', 'haricot'),
('legumes', 'Petit pois', 'petit pois'),
('legumes', 'Celeri', 'celeri'),
('legumes', 'Champignon', 'champignon'),
('legumes', 'Patate douce', 'patate douce'),

('couleurs', 'Indigo', 'indigo'),
('couleurs', 'Cyan', 'cyan'),
('couleurs', 'Ocre', 'ocre'),
('couleurs', 'Lavande', 'lavande'),
('couleurs', 'Magenta', 'magenta'),

('sports', 'Karate', 'karate'),
('sports', 'Surf', 'surf'),
('sports', 'Ski', 'ski'),
('sports', 'Patinage', 'patinage'),
('sports', 'Triathlon', 'triathlon'),

('metiers', 'Pharmacien', 'pharmacien'),
('metiers', 'Dentiste', 'dentiste'),
('metiers', 'Veterinaire', 'veterinaire'),
('metiers', 'Developpeur', 'developpeur'),
('metiers', 'Plombier', 'plombier'),

('capitales', 'Stockholm', 'stockholm'),
('capitales', 'Oslo', 'oslo'),
('capitales', 'Helsinki', 'helsinki'),
('capitales', 'Pekin', 'pekin'),
('capitales', 'Wellington', 'wellington'),

('instruments', 'Mandoline', 'mandoline'),
('instruments', 'Xylophone', 'xylophone'),
('instruments', 'Banjo', 'banjo'),
('instruments', 'Tambourin', 'tambourin'),
('instruments', 'Cornemuse', 'cornemuse'),

('vehicules', 'Scooter', 'scooter'),
('vehicules', 'Kayak', 'kayak'),
('vehicules', 'Canoe', 'canoe'),
('vehicules', 'Zeppelin', 'zeppelin'),
('vehicules', 'Remorque', 'remorque'),

('fleurs', 'Jonquille', 'jonquille'),
('fleurs', 'Begonia', 'begonia'),
('fleurs', 'Anemone', 'anemone'),
('fleurs', 'Lotus', 'lotus'),
('fleurs', 'Geranium', 'geranium'),

('emotions', 'Gratitude', 'gratitude'),
('emotions', 'Serenite', 'serenite'),
('emotions', 'Jalousie', 'jalousie'),
('emotions', 'Espoir', 'espoir'),
('emotions', 'Admiration', 'admiration'),

('vetements', 'Gants', 'gants'),
('vetements', 'Chaussettes', 'chaussettes'),
('vetements', 'Short', 'short'),
('vetements', 'Blazer', 'blazer'),
('vetements', 'Pyjama', 'pyjama'),

('boissons', 'Eau gazeuse', 'eau gazeuse'),
('boissons', 'Jus pomme', 'jus pomme'),
('boissons', 'Jus orange', 'jus orange'),
('boissons', 'Matcha', 'matcha'),
('boissons', 'Cidre', 'cidre'),
('boissons', 'Coca Cola', 'coca cola'),
('boissons', 'Pepsi', 'pepsi'),
('boissons', 'Fanta', 'fanta'),
('boissons', 'Sprite', 'sprite'),
('boissons', 'Orangina', 'orangina'),
('boissons', 'Red Bull', 'red bull'),
('boissons', 'Monster', 'monster'),
('boissons', 'Lipton Ice Tea', 'lipton ice tea'),
('boissons', 'Oasis', 'oasis'),
('boissons', 'Schweppes', 'schweppes'),
('boissons', 'Perrier', 'perrier'),
('boissons', 'Evian', 'evian'),
('boissons', 'Badoit', 'badoit'),
('boissons', 'San Pellegrino', 'san pellegrino'),
('boissons', 'Tropicana', 'tropicana'),
('boissons', 'Capri Sun', 'capri sun'),
('boissons', 'Gatorade', 'gatorade'),
('boissons', 'Powerade', 'powerade'),

('desserts', 'Millefeuille', 'millefeuille'),
('desserts', 'Profiterole', 'profiterole'),
('desserts', 'Meringue', 'meringue'),
('desserts', 'Cheesecake', 'cheesecake'),
('desserts', 'Clafoutis', 'clafoutis'),

('objets_maison', 'Balai', 'balai'),
('objets_maison', 'Seau', 'seau'),
('objets_maison', 'Tapis', 'tapis'),
('objets_maison', 'Rideau', 'rideau'),
('objets_maison', 'Miroir', 'miroir'),

('cinema', 'Godzilla', 'godzilla'),
('cinema', 'Vertigo', 'vertigo'),
('cinema', 'Casablanca', 'casablanca'),
('cinema', 'Whiplash', 'whiplash'),
('cinema', 'Barbie', 'barbie'),

('jeux_video', 'Halo', 'halo'),
('jeux_video', 'Portal', 'portal'),
('jeux_video', 'Celeste', 'celeste'),
('jeux_video', 'Hades', 'hades'),
('jeux_video', 'Uncharted', 'uncharted'),

('sciences', 'Microbiologie', 'microbiologie'),
('sciences', 'Neurosciences', 'neurosciences'),
('sciences', 'Algebre', 'algebre'),
('sciences', 'Robotique', 'robotique'),
('sciences', 'Cryptographie', 'cryptographie'),

('musique', 'Opera', 'opera'),
('musique', 'House', 'house'),
('musique', 'Drill', 'drill'),
('musique', 'Afrobeat', 'afrobeat'),
('musique', 'Kpop', 'kpop'),

('fruits', 'Mandarine', 'mandarine'),
('fruits', 'Pamplemousse', 'pamplemousse'),
('fruits', 'Noix de coco', 'noix de coco'),
('fruits', 'Litchi', 'litchi'),
('fruits', 'Datte', 'datte'),

('animaux', 'Singe', 'singe'),
('animaux', 'Serpent', 'serpent'),
('animaux', 'Hibou', 'hibou'),
('animaux', 'Pingouin', 'pingouin'),
('animaux', 'Crocodile', 'crocodile'),

('pays', 'Etats Unis', 'etats unis'),
('pays', 'Royaume Uni', 'royaume uni'),
('pays', 'Pays Bas', 'pays bas'),
('pays', 'Coree du Sud', 'coree du sud'),
('pays', 'Afrique du Sud', 'afrique du sud'),

('legumes', 'Artichaut', 'artichaut'),
('legumes', 'Asperge', 'asperge'),
('legumes', 'Betterave', 'betterave'),
('legumes', 'Courge', 'courge'),
('legumes', 'Fenouil', 'fenouil'),

('couleurs', 'Bordeaux', 'bordeaux'),
('couleurs', 'Saumon', 'saumon'),
('couleurs', 'Kaki', 'kaki'),
('couleurs', 'Ambre', 'ambre'),
('couleurs', 'Ivoire', 'ivoire'),

('sports', 'Baseball', 'baseball'),
('sports', 'Hockey', 'hockey'),
('sports', 'Petanque', 'petanque'),
('sports', 'Gymnastique', 'gymnastique'),
('sports', 'Marathon', 'marathon'),

('metiers', 'Comptable', 'comptable'),
('metiers', 'Banquier', 'banquier'),
('metiers', 'Notaire', 'notaire'),
('metiers', 'Electricien', 'electricien'),
('metiers', 'Menuisier', 'menuisier'),

('capitales', 'Londres', 'londres'),
('capitales', 'Washington', 'washington'),
('capitales', 'Amsterdam', 'amsterdam'),
('capitales', 'Athenes', 'athenes'),
('capitales', 'Dublin', 'dublin'),

('instruments', 'Harmonica', 'harmonica'),
('instruments', 'Clavecin', 'clavecin'),
('instruments', 'Didgeridoo', 'didgeridoo'),
('instruments', 'Synthetiseur', 'synthetiseur'),
('instruments', 'Djembe', 'djembe'),

('vehicules', 'Monospace', 'monospace'),
('vehicules', 'Pickup', 'pickup'),
('vehicules', 'Motoneige', 'motoneige'),
('vehicules', 'Voilier', 'voilier'),
('vehicules', 'Fusee', 'fusee'),

('fleurs', 'Narcisse', 'narcisse'),
('fleurs', 'Dahlia', 'dahlia'),
('fleurs', 'Camomille', 'camomille'),
('fleurs', 'Lilas', 'lilas'),
('fleurs', 'Pissenlit', 'pissenlit'),

('emotions', 'Melancolie', 'melancolie'),
('emotions', 'Compassion', 'compassion'),
('emotions', 'Soulagement', 'soulagement'),
('emotions', 'Impatience', 'impatience'),
('emotions', 'Culpabilite', 'culpabilite'),

('vetements', 'Cardigan', 'cardigan'),
('vetements', 'Sweat', 'sweat'),
('vetements', 'Cravate', 'cravate'),
('vetements', 'Maillot', 'maillot'),
('vetements', 'Baskets', 'baskets'),

('desserts', 'Crumble', 'crumble'),
('desserts', 'Madeleine', 'madeleine'),
('desserts', 'Fondant', 'fondant'),
('desserts', 'Beignet', 'beignet'),
('desserts', 'Tarte tatin', 'tarte tatin'),

('objets_maison', 'Bureau', 'bureau'),
('objets_maison', 'Etagere', 'etagere'),
('objets_maison', 'Horloge', 'horloge'),
('objets_maison', 'Coussin', 'coussin'),
('objets_maison', 'Aspirateur', 'aspirateur'),

('cinema', 'Oppenheimer', 'oppenheimer'),
('cinema', 'Le Parrain', 'le parrain'),
('cinema', 'Pulp Fiction', 'pulp fiction'),
('cinema', 'Fight Club', 'fight club'),
('cinema', 'Intouchables', 'intouchables'),

('jeux_video', 'League of Legends', 'league of legends'),
('jeux_video', 'Counter Strike', 'counter strike'),
('jeux_video', 'GTA', 'gta'),
('jeux_video', 'Apex Legends', 'apex legends'),
('jeux_video', 'Elden Ring', 'elden ring'),

('sciences', 'Thermodynamique', 'thermodynamique'),
('sciences', 'Astrophysique', 'astrophysique'),
('sciences', 'Biochimie', 'biochimie'),
('sciences', 'Epidemiologie', 'epidemiologie'),
('sciences', 'Nanotechnologie', 'nanotechnologie'),

('musique', 'Rnb', 'rnb'),
('musique', 'Trap', 'trap'),
('musique', 'Folk', 'folk'),
('musique', 'Grunge', 'grunge'),
('musique', 'Flamenco', 'flamenco'),

('fruits', 'Clementine', 'clementine'),
('fruits', 'Goyave', 'goyave'),
('fruits', 'Papaye', 'papaye'),

('animaux', 'Gorille', 'gorille'),
('animaux', 'Hippopotame', 'hippopotame'),
('animaux', 'Rhinoceros', 'rhinoceros'),
('animaux', 'Poule', 'poule'),

('pays', 'Russie', 'russie'),
('pays', 'Ukraine', 'ukraine'),
('pays', 'Turquie', 'turquie'),
('pays', 'Grece', 'grece'),
('pays', 'Autriche', 'autriche'),
('pays', 'Irlande', 'irlande'),

('legumes', 'Salade', 'salade'),
('legumes', 'Chou fleur', 'chou fleur'),
('legumes', 'Haricot vert', 'haricot vert'),

('couleurs', 'Bleu marine', 'bleu marine'),
('couleurs', 'Fuchsia', 'fuchsia'),

('sports', 'Ping pong', 'ping pong'),
('sports', 'Halterophilie', 'halterophilie'),

('metiers', 'Psychologue', 'psychologue'),

('capitales', 'Moscou', 'moscou'),

('instruments', 'Triangle', 'triangle'),

('vehicules', 'Sous marin', 'sous marin'),

('vetements', 'Casquette', 'casquette'),

('boissons', 'Sodas', 'sodas'),
('boissons', 'Heineken', 'heineken'),
('boissons', 'Nespresso', 'nespresso'),
('boissons', 'Desperados', 'desperados'),
('boissons', 'Ice tea', 'ice tea'),
('boissons', 'Fuze Tea', 'fuze tea'),
('boissons', 'Nestea', 'nestea'),
('boissons', 'Arizona', 'arizona'),
('boissons', 'Minute Maid', 'minute maid'),
('boissons', 'Granini', 'granini'),
('boissons', 'Joker', 'joker'),
('boissons', 'Pago', 'pago'),
('boissons', 'Innocent', 'innocent'),
('boissons', 'Pressade', 'pressade'),
('boissons', 'Jus ananas', 'jus ananas'),
('boissons', 'Jus raisin', 'jus raisin'),
('boissons', 'Jus tomate', 'jus tomate'),
('boissons', 'Jus mangue', 'jus mangue'),
('boissons', 'Jus multifruits', 'jus multifruits'),
('boissons', 'Nectar', 'nectar'),

('objets_maison', 'Frigo', 'frigo'),

('cinema', 'Avengers', 'avengers'),
('cinema', 'Star Wars', 'star wars'),
('cinema', 'Forrest Gump', 'forrest gump'),

('jeux_video', 'Call of Duty', 'call of duty'),
('jeux_video', 'Assassins Creed', 'assassins creed'),
('jeux_video', 'World of Warcraft', 'world of warcraft'),

('sciences', 'IA', 'ia'),
('sciences', 'Quantique', 'quantique'),
('sciences', 'Machine learning', 'machine learning'),

('musique', 'Hip hop', 'hip hop'),
('musique', 'Hiphop', 'hiphop'),
('musique', 'Lo fi', 'lo fi'),

('fruits', 'Nectarine', 'nectarine'),
('fruits', 'Mirabelle', 'mirabelle'),
('fruits', 'Mure', 'mure'),
('fruits', 'Cassis', 'cassis'),
('fruits', 'Groseille', 'groseille'),
('fruits', 'Pamplemousse rose', 'pamplemousse rose'),
('fruits', 'Citron vert', 'citron vert'),
('fruits', 'Fruit de la passion', 'fruit de la passion'),
('fruits', 'Kaki', 'kaki'),
('fruits', 'Cranberry', 'cranberry'),
('fruits', 'Cassis noir', 'cassis noir'),
('fruits', 'Pruneau', 'pruneau'),
('fruits', 'Coing', 'coing'),
('fruits', 'Carambole', 'carambole'),
('fruits', 'Kumquat', 'kumquat'),
('fruits', 'Pomelo', 'pomelo'),
('fruits', 'Grenadille', 'grenadille'),
('fruits', 'Baie de goji', 'baie de goji'),
('fruits', 'Mangoustan', 'mangoustan'),
('fruits', 'Cacao', 'cacao'),
('fruits', 'Tangerine', 'tangerine'),
('fruits', 'Yuzu', 'yuzu'),
('fruits', 'Bergamote', 'bergamote'),
('fruits', 'Cedrat', 'cedrat'),
('fruits', 'Banane plantain', 'banane plantain'),
('fruits', 'Airelle', 'airelle'),
('fruits', 'Canneberge', 'canneberge'),
('fruits', 'Physalis', 'physalis'),
('fruits', 'Mure sauvage', 'mure sauvage'),
('fruits', 'Baie d argousier', 'baie d argousier'),
('fruits', 'Baie de sureau', 'baie de sureau'),
('fruits', 'Baie de genevre', 'baie de genevre'),
('fruits', 'Melon charentais', 'melon charentais'),
('fruits', 'Melon jaune', 'melon jaune'),
('fruits', 'Fruit du dragon', 'fruit du dragon'),
('fruits', 'Pitaya', 'pitaya'),
('fruits', 'Ramboutan', 'ramboutan'),
('fruits', 'Longane', 'longane'),
('fruits', 'Durian', 'durian'),
('fruits', 'Salak', 'salak'),
('fruits', 'Jacquier', 'jacquier'),
('fruits', 'Corossol', 'corossol'),
('fruits', 'Sapotille', 'sapotille'),
('fruits', 'Feijoa', 'feijoa'),
('fruits', 'Nashi', 'nashi'),
('fruits', 'Jujube', 'jujube'),
('fruits', 'Arbouse', 'arbouse'),
('fruits', 'Cynorrhodon', 'cynorrhodon'),
('fruits', 'Nefle', 'nefle'),
('fruits', 'Nefle du Japon', 'nefle du japon'),
('fruits', 'Asimine', 'asimine'),
('fruits', 'Tamarin', 'tamarin'),
('fruits', 'Quetsche', 'quetsche'),
('fruits', 'Reine claude', 'reine claude'),
('fruits', 'Prunelle', 'prunelle'),
('fruits', 'Baie d aronia', 'baie d aronia'),
('fruits', 'Olive', 'olive'),
('fruits', 'Avocat', 'avocat'),
('fruits', 'Rhubarbe', 'rhubarbe'),
('fruits', 'Figue de barbarie', 'figue de barbarie'),
('fruits', 'Noix', 'noix'),
('fruits', 'Amande', 'amande'),
('fruits', 'Noisette', 'noisette'),
('fruits', 'Pistache', 'pistache'),
('fruits', 'Pacane', 'pacane'),
('fruits', 'Macadamia', 'macadamia'),
('fruits', 'Pecan', 'pecan'),
('fruits', 'Noix du Bresil', 'noix du bresil'),

('animaux', 'Mouton', 'mouton'),
('animaux', 'Chevre', 'chevre'),
('animaux', 'Cochon', 'cochon'),
('animaux', 'Canard', 'canard'),
('animaux', 'Oie', 'oie'),
('animaux', 'Dinde', 'dinde'),
('animaux', 'Chouette', 'chouette'),
('animaux', 'Perroquet', 'perroquet'),
('animaux', 'Moineau', 'moineau'),
('animaux', 'Corbeau', 'corbeau'),
('animaux', 'Faucon', 'faucon'),
('animaux', 'Phoque', 'phoque'),
('animaux', 'Otarie', 'otarie'),
('animaux', 'Pieuvre', 'pieuvre'),
('animaux', 'Requin', 'requin'),
('animaux', 'Raie', 'raie'),
('animaux', 'Meduse', 'meduse'),
('animaux', 'Crabe', 'crabe'),
('animaux', 'Homard', 'homard'),
('animaux', 'Ecureuil', 'ecureuil'),

('pays', 'Danemark', 'danemark'),
('pays', 'Islande', 'islande'),
('pays', 'Pologne', 'pologne'),
('pays', 'Hongrie', 'hongrie'),
('pays', 'Roumanie', 'roumanie'),
('pays', 'Bulgarie', 'bulgarie'),
('pays', 'Croatie', 'croatie'),
('pays', 'Serbie', 'serbie'),
('pays', 'Algerie', 'algerie'),
('pays', 'Tunisie', 'tunisie'),
('pays', 'Nigeria', 'nigeria'),
('pays', 'Kenya', 'kenya'),
('pays', 'Senegal', 'senegal'),
('pays', 'Perou', 'perou'),
('pays', 'Chili', 'chili'),
('pays', 'Colombie', 'colombie'),
('pays', 'Thailande', 'thailande'),
('pays', 'Vietnam', 'vietnam'),
('pays', 'Indonesie', 'indonesie'),
('pays', 'Nouvelle Zelande', 'nouvelle zelande'),

('legumes', 'Potiron', 'potiron'),
('legumes', 'Potimarron', 'potimarron'),
('legumes', 'Butternut', 'butternut'),
('legumes', 'Endive', 'endive'),
('legumes', 'Blette', 'blette'),
('legumes', 'Chou rouge', 'chou rouge'),
('legumes', 'Chou vert', 'chou vert'),
('legumes', 'Pois chiche', 'pois chiche'),
('legumes', 'Lentille', 'lentille'),
('legumes', 'Mais', 'mais'),
('legumes', 'Topinambour', 'topinambour'),
('legumes', 'Rutabaga', 'rutabaga'),
('legumes', 'Salsifis', 'salsifis'),
('legumes', 'Pois mange tout', 'pois mange tout'),
('legumes', 'Panais', 'panais'),
('legumes', 'Cresson', 'cresson'),
('legumes', 'Roquette', 'roquette'),
('legumes', 'Avocat', 'avocat'),
('legumes', 'Manioc', 'manioc'),
('legumes', 'Pois casses', 'pois casses'),

('couleurs', 'Turquin', 'turquin'),
('couleurs', 'Olive', 'olive'),
('couleurs', 'Corail', 'corail'),
('couleurs', 'Brique', 'brique'),
('couleurs', 'Moutarde', 'moutarde'),
('couleurs', 'Menthe', 'menthe'),
('couleurs', 'Prune', 'prune'),
('couleurs', 'Aubergine', 'aubergine'),
('couleurs', 'Taupe', 'taupe'),
('couleurs', 'Sable', 'sable'),
('couleurs', 'Caramel', 'caramel'),
('couleurs', 'Chocolat', 'chocolat'),
('couleurs', 'Cuivre', 'cuivre'),
('couleurs', 'Bronze', 'bronze'),
('couleurs', 'Perle', 'perle'),
('couleurs', 'Emeraude', 'emeraude'),
('couleurs', 'Rubis', 'rubis'),
('couleurs', 'Saphir', 'saphir'),
('couleurs', 'Lilas', 'lilas'),
('couleurs', 'Anthracite', 'anthracite'),
('couleurs', 'Azur', 'azur'),
('couleurs', 'Aigue marine', 'aigue marine'),
('couleurs', 'Aquamarine', 'aquamarine'),
('couleurs', 'Ardoise', 'ardoise'),
('couleurs', 'Bistre', 'bistre'),
('couleurs', 'Blond', 'blond'),
('couleurs', 'Bouton d or', 'bouton d or'),
('couleurs', 'Cacao', 'cacao'),
('couleurs', 'Canari', 'canari'),
('couleurs', 'Cendre', 'cendre'),
('couleurs', 'Cerise', 'cerise'),
('couleurs', 'Chartreuse', 'chartreuse'),
('couleurs', 'Chataigne', 'chataigne'),
('couleurs', 'Citron', 'citron'),
('couleurs', 'Cobalt', 'cobalt'),
('couleurs', 'Coquelicot', 'coquelicot'),
('couleurs', 'Crimson', 'crimson'),
('couleurs', 'Creme', 'creme'),
('couleurs', 'Ebene', 'ebene'),
('couleurs', 'Ecru', 'ecru'),
('couleurs', 'Ecarlate', 'ecarlate'),
('couleurs', 'Encre', 'encre'),
('couleurs', 'Fauve', 'fauve'),
('couleurs', 'Flamme', 'flamme'),
('couleurs', 'Framboise', 'framboise'),
('couleurs', 'Fraise', 'fraise'),
('couleurs', 'Garance', 'garance'),
('couleurs', 'Glacier', 'glacier'),
('couleurs', 'Grenat', 'grenat'),
('couleurs', 'Grège', 'grege'),
('couleurs', 'Groseille', 'groseille'),
('couleurs', 'Havane', 'havane'),
('couleurs', 'Isabelle', 'isabelle'),
('couleurs', 'Jade', 'jade'),
('couleurs', 'Jonquille', 'jonquille'),
('couleurs', 'Lagon', 'lagon'),
('couleurs', 'Lierre', 'lierre'),
('couleurs', 'Lin', 'lin'),
('couleurs', 'Mandarine', 'mandarine'),
('couleurs', 'Mauve', 'mauve'),
('couleurs', 'Miel', 'miel'),
('couleurs', 'Mocha', 'mocha'),
('couleurs', 'Nacre', 'nacre'),
('couleurs', 'Navy', 'navy'),
('couleurs', 'Noisette', 'noisette'),
('couleurs', 'Occre jaune', 'occre jaune'),
('couleurs', 'Opaline', 'opaline'),
('couleurs', 'Orchidee', 'orchidee'),
('couleurs', 'Orpiment', 'orpiment'),
('couleurs', 'Paille', 'paille'),
('couleurs', 'Papaye', 'papaye'),
('couleurs', 'Pervenche', 'pervenche'),
('couleurs', 'Pistache', 'pistache'),
('couleurs', 'Platinium', 'platinium'),
('couleurs', 'Pourpre', 'pourpre'),
('couleurs', 'Poussin', 'poussin'),
('couleurs', 'Roux', 'roux'),
('couleurs', 'Sang de boeuf', 'sang de boeuf'),
('couleurs', 'Sepia', 'sepia'),
('couleurs', 'Topaze', 'topaze'),
('couleurs', 'Vanille', 'vanille'),
('couleurs', 'Vermeil', 'vermeil'),
('couleurs', 'Veronese', 'veronese'),
('couleurs', 'Vieil or', 'vieil or'),
('couleurs', 'Zinzolin', 'zinzolin'),
('couleurs', 'Bleu ciel', 'bleu ciel'),
('couleurs', 'Bleu roi', 'bleu roi'),
('couleurs', 'Bleu nuit', 'bleu nuit'),
('couleurs', 'Bleu canard', 'bleu canard'),
('couleurs', 'Bleu petrole', 'bleu petrole'),
('couleurs', 'Vert anis', 'vert anis'),
('couleurs', 'Vert pomme', 'vert pomme'),
('couleurs', 'Vert sapin', 'vert sapin'),
('couleurs', 'Vert bouteille', 'vert bouteille'),
('couleurs', 'Vert d eau', 'vert d eau'),
('couleurs', 'Vert kaki', 'vert kaki'),
('couleurs', 'Jaune citron', 'jaune citron'),
('couleurs', 'Jaune paille', 'jaune paille'),
('couleurs', 'Jaune d or', 'jaune d or'),
('couleurs', 'Orange sanguine', 'orange sanguine'),
('couleurs', 'Orange brule', 'orange brule'),
('couleurs', 'Rouge carmin', 'rouge carmin'),
('couleurs', 'Rouge cerise', 'rouge cerise'),
('couleurs', 'Rouge brique', 'rouge brique'),
('couleurs', 'Rouge vermillon', 'rouge vermillon'),
('couleurs', 'Rouge grenat', 'rouge grenat'),
('couleurs', 'Rose pale', 'rose pale'),
('couleurs', 'Rose bonbon', 'rose bonbon'),
('couleurs', 'Rose poudre', 'rose poudre'),
('couleurs', 'Rose saumon', 'rose saumon'),
('couleurs', 'Violet prune', 'violet prune'),
('couleurs', 'Violet amethyste', 'violet amethyste'),
('couleurs', 'Violet imperial', 'violet imperial'),
('couleurs', 'Gris souris', 'gris souris'),
('couleurs', 'Gris perle', 'gris perle'),
('couleurs', 'Gris clair', 'gris clair'),
('couleurs', 'Gris fonce', 'gris fonce'),
('couleurs', 'Blanc casse', 'blanc casse'),
('couleurs', 'Blanc ivoire', 'blanc ivoire'),
('couleurs', 'Blanc neige', 'blanc neige'),
('couleurs', 'Noir corbeau', 'noir corbeau'),
('couleurs', 'Noir jais', 'noir jais'),
('couleurs', 'Marron glace', 'marron glace'),
('couleurs', 'Marron chocolat', 'marron chocolat'),
('couleurs', 'Marron noisette', 'marron noisette'),

('sports', 'Taekwondo', 'taekwondo'),
('sports', 'Aviron', 'aviron'),
('sports', 'Voile', 'voile'),
('sports', 'Plongee', 'plongee'),
('sports', 'Canoe kayak', 'canoe kayak'),
('sports', 'Lutte', 'lutte'),
('sports', 'BMX', 'bmx'),
('sports', 'Skateboard', 'skateboard'),
('sports', 'Snowboard', 'snowboard'),
('sports', 'Biathlon', 'biathlon'),
('sports', 'Curling', 'curling'),
('sports', 'Squash', 'squash'),
('sports', 'Padel', 'padel'),
('sports', 'Water polo', 'water polo'),
('sports', 'Lancer de javelot', 'lancer de javelot'),
('sports', 'Decathlon', 'decathlon'),
('sports', 'Course a pied', 'course a pied'),
('sports', 'Equitation', 'equitation'),
('sports', 'Tir a l arc', 'tir a l arc'),
('sports', 'MMA', 'mma'),

('metiers', 'Boucher', 'boucher'),
('metiers', 'Patissier', 'patissier'),
('metiers', 'Serveur', 'serveur'),
('metiers', 'Receptionniste', 'receptionniste'),
('metiers', 'Agriculteur', 'agriculteur'),
('metiers', 'Maraicher', 'maraicher'),
('metiers', 'Bricoleur', 'bricoleur'),
('metiers', 'Soudeur', 'soudeur'),
('metiers', 'Carreleur', 'carreleur'),
('metiers', 'Macon', 'macon'),
('metiers', 'Conducteur', 'conducteur'),
('metiers', 'Pilote', 'pilote'),
('metiers', 'Hotesse de l air', 'hotesse de l air'),
('metiers', 'Traducteur', 'traducteur'),
('metiers', 'Bibliothecaire', 'bibliothecaire'),
('metiers', 'Chercheur', 'chercheur'),
('metiers', 'Photographe', 'photographe'),
('metiers', 'Designer', 'designer'),
('metiers', 'Community manager', 'community manager'),
('metiers', 'Caissier', 'caissier'),

('capitales', 'Copenhague', 'copenhague'),
('capitales', 'Reykjavik', 'reykjavik'),
('capitales', 'Varsovie', 'varsovie'),
('capitales', 'Budapest', 'budapest'),
('capitales', 'Bucarest', 'bucarest'),
('capitales', 'Sofia', 'sofia'),
('capitales', 'Zagreb', 'zagreb'),
('capitales', 'Belgrade', 'belgrade'),
('capitales', 'Alger', 'alger'),
('capitales', 'Tunis', 'tunis'),
('capitales', 'Abuja', 'abuja'),
('capitales', 'Nairobi', 'nairobi'),
('capitales', 'Dakar', 'dakar'),
('capitales', 'Lima', 'lima'),
('capitales', 'Santiago', 'santiago'),
('capitales', 'Bogota', 'bogota'),
('capitales', 'Bangkok', 'bangkok'),
('capitales', 'Hanoi', 'hanoi'),
('capitales', 'Jakarta', 'jakarta'),
('capitales', 'Kaboul', 'kaboul'),
('capitales', 'Pretoria', 'pretoria'),
('capitales', 'Tirane', 'tirane'),
('capitales', 'Andorre la Vieille', 'andorre la vieille'),
('capitales', 'Luanda', 'luanda'),
('capitales', 'Saint Johns', 'saint johns'),
('capitales', 'Erevan', 'erevan'),
('capitales', 'Vienne', 'vienne'),
('capitales', 'Bakou', 'bakou'),
('capitales', 'Nassau', 'nassau'),
('capitales', 'Manama', 'manama'),
('capitales', 'Dacca', 'dacca'),
('capitales', 'Bridgetown', 'bridgetown'),
('capitales', 'Minsk', 'minsk'),
('capitales', 'Belmopan', 'belmopan'),
('capitales', 'Porto Novo', 'porto novo'),
('capitales', 'Thimphou', 'thimphou'),
('capitales', 'La Paz', 'la paz'),
('capitales', 'Sucre', 'sucre'),
('capitales', 'Sarajevo', 'sarajevo'),
('capitales', 'Gaborone', 'gaborone'),
('capitales', 'Bandar Seri Begawan', 'bandar seri begawan'),
('capitales', 'Ouagadougou', 'ouagadougou'),
('capitales', 'Gitega', 'gitega'),
('capitales', 'Phnom Penh', 'phnom penh'),
('capitales', 'Yaounde', 'yaounde'),
('capitales', 'Praia', 'praia'),
('capitales', 'Bangui', 'bangui'),
('capitales', 'Ndjamena', 'ndjamena'),
('capitales', 'Moroni', 'moroni'),
('capitales', 'Brazzaville', 'brazzaville'),
('capitales', 'Kinshasa', 'kinshasa'),
('capitales', 'San Jose', 'san jose'),
('capitales', 'Yamoussoukro', 'yamoussoukro'),
('capitales', 'Nicosie', 'nicosie'),
('capitales', 'Prague', 'prague'),
('capitales', 'Djibouti', 'djibouti'),
('capitales', 'Roseau', 'roseau'),
('capitales', 'Saint Domingue', 'saint domingue'),
('capitales', 'Quito', 'quito'),
('capitales', 'San Salvador', 'san salvador'),
('capitales', 'Malabo', 'malabo'),
('capitales', 'Asmara', 'asmara'),
('capitales', 'Tallinn', 'tallinn'),
('capitales', 'Mbabane', 'mbabane'),
('capitales', 'Addis Abeba', 'addis abeba'),
('capitales', 'Suva', 'suva'),
('capitales', 'Libreville', 'libreville'),
('capitales', 'Banjul', 'banjul'),
('capitales', 'Tbilissi', 'tbilissi'),
('capitales', 'Accra', 'accra'),
('capitales', 'Saint Georges', 'saint georges'),
('capitales', 'Guatemala', 'guatemala'),
('capitales', 'Conakry', 'conakry'),
('capitales', 'Bissau', 'bissau'),
('capitales', 'Georgetown', 'georgetown'),
('capitales', 'Port au Prince', 'port au prince'),
('capitales', 'Tegucigalpa', 'tegucigalpa'),
('capitales', 'New Delhi', 'new delhi'),
('capitales', 'Teheran', 'teheran'),
('capitales', 'Bagdad', 'bagdad'),
('capitales', 'Jerusalem', 'jerusalem'),
('capitales', 'Amman', 'amman'),
('capitales', 'Astana', 'astana'),
('capitales', 'Noursoultan', 'noursoultan'),
('capitales', 'Tarawa Sud', 'tarawa sud'),
('capitales', 'Pristina', 'pristina'),
('capitales', 'Koweit', 'koweit'),
('capitales', 'Bichkek', 'bichkek'),
('capitales', 'Vientiane', 'vientiane'),
('capitales', 'Riga', 'riga'),
('capitales', 'Beyrouth', 'beyrouth'),
('capitales', 'Maseru', 'maseru'),
('capitales', 'Monrovia', 'monrovia'),
('capitales', 'Tripoli', 'tripoli'),
('capitales', 'Vaduz', 'vaduz'),
('capitales', 'Vilnius', 'vilnius'),
('capitales', 'Luxembourg', 'luxembourg'),
('capitales', 'Antananarivo', 'antananarivo'),
('capitales', 'Lilongwe', 'lilongwe'),
('capitales', 'Kuala Lumpur', 'kuala lumpur'),
('capitales', 'Male', 'male'),
('capitales', 'Bamako', 'bamako'),
('capitales', 'La Valette', 'la valette'),
('capitales', 'Majuro', 'majuro'),
('capitales', 'Nouakchott', 'nouakchott'),
('capitales', 'Port Louis', 'port louis'),
('capitales', 'Palikir', 'palikir'),
('capitales', 'Chisinau', 'chisinau'),
('capitales', 'Monaco', 'monaco'),
('capitales', 'Oulan Bator', 'oulan bator'),
('capitales', 'Podgorica', 'podgorica'),
('capitales', 'Maputo', 'maputo'),
('capitales', 'Naypyidaw', 'naypyidaw'),
('capitales', 'Windhoek', 'windhoek'),
('capitales', 'Yaren', 'yaren'),
('capitales', 'Katmandou', 'katmandou'),
('capitales', 'Managua', 'managua'),
('capitales', 'Niamey', 'niamey'),
('capitales', 'Pyongyang', 'pyongyang'),
('capitales', 'Skopje', 'skopje'),
('capitales', 'Mascate', 'mascate'),
('capitales', 'Islamabad', 'islamabad'),
('capitales', 'Ngerulmud', 'ngerulmud'),
('capitales', 'Panama', 'panama'),
('capitales', 'Port Moresby', 'port moresby'),
('capitales', 'Asuncion', 'asuncion'),
('capitales', 'Manille', 'manille'),
('capitales', 'Doha', 'doha'),
('capitales', 'Kigali', 'kigali'),
('capitales', 'Basseterre', 'basseterre'),
('capitales', 'Castries', 'castries'),
('capitales', 'Kingstown', 'kingstown'),
('capitales', 'Apia', 'apia'),
('capitales', 'Saint Marin', 'saint marin'),
('capitales', 'Sao Tome', 'sao tome'),
('capitales', 'Riyad', 'riyad'),
('capitales', 'Freetown', 'freetown'),
('capitales', 'Singapour', 'singapour'),
('capitales', 'Bratislava', 'bratislava'),
('capitales', 'Ljubljana', 'ljubljana'),
('capitales', 'Honiara', 'honiara'),
('capitales', 'Mogadiscio', 'mogadiscio'),
('capitales', 'Juba', 'juba'),
('capitales', 'Sri Jayawardenepura Kotte', 'sri jayawardenepura kotte'),
('capitales', 'Khartoum', 'khartoum'),
('capitales', 'Paramaribo', 'paramaribo'),
('capitales', 'Berne', 'berne'),
('capitales', 'Damas', 'damas'),
('capitales', 'Douchanbe', 'douchanbe'),
('capitales', 'Dodoma', 'dodoma'),
('capitales', 'Lome', 'lome'),
('capitales', 'Nukualofa', 'nukualofa'),
('capitales', 'Port of Spain', 'port of spain'),
('capitales', 'Ankara', 'ankara'),
('capitales', 'Achgabat', 'achgabat'),
('capitales', 'Funafuti', 'funafuti'),
('capitales', 'Kampala', 'kampala'),
('capitales', 'Kiev', 'kiev'),
('capitales', 'Abou Dabi', 'abou dabi'),
('capitales', 'Montevideo', 'montevideo'),
('capitales', 'Tachkent', 'tachkent'),
('capitales', 'Port Vila', 'port vila'),
('capitales', 'Vatican', 'vatican'),
('capitales', 'Caracas', 'caracas'),
('capitales', 'Sanaa', 'sanaa'),
('capitales', 'Lusaka', 'lusaka'),
('capitales', 'Harare', 'harare'),

('instruments', 'Viola', 'viola'),
('instruments', 'Piccolo', 'piccolo'),
('instruments', 'Tuba', 'tuba'),
('instruments', 'Ocarina', 'ocarina'),
('instruments', 'Castagnettes', 'castagnettes'),
('instruments', 'Conga', 'conga'),
('instruments', 'Bongo', 'bongo'),
('instruments', 'Maracas', 'maracas'),
('instruments', 'Gong', 'gong'),
('instruments', 'Cymbales', 'cymbales'),
('instruments', 'Kalimba', 'kalimba'),
('instruments', 'Balalaika', 'balalaika'),
('instruments', 'Luth', 'luth'),
('instruments', 'Vibraphone', 'vibraphone'),
('instruments', 'Mellophone', 'mellophone'),
('instruments', 'Cor', 'cor'),
('instruments', 'Cajon', 'cajon'),
('instruments', 'Melodica', 'melodica'),
('instruments', 'Flute traversiere', 'flute traversiere'),
('instruments', 'Orgue', 'orgue'),

('vehicules', 'Berline', 'berline'),
('vehicules', 'Cabriolet', 'cabriolet'),
('vehicules', 'SUV', 'suv'),
('vehicules', 'Camping car', 'camping car'),
('vehicules', 'Minibus', 'minibus'),
('vehicules', 'TGV', 'tgv'),
('vehicules', 'Jet ski', 'jet ski'),
('vehicules', 'Yacht', 'yacht'),
('vehicules', 'Peniche', 'peniche'),
('vehicules', 'Montgolfiere', 'montgolfiere'),
('vehicules', 'Deltaplane', 'deltaplane'),
('vehicules', 'ULM', 'ulm'),
('vehicules', 'Chariot', 'chariot'),
('vehicules', 'Quad', 'quad'),
('vehicules', 'Buggy', 'buggy'),
('vehicules', 'Kart', 'kart'),
('vehicules', 'Ambulance', 'ambulance'),
('vehicules', 'Depanneuse', 'depanneuse'),
('vehicules', 'Bulldozer', 'bulldozer'),
('vehicules', 'Pelleteuse', 'pelleteuse'),

('fleurs', 'Azalee', 'azalee'),
('fleurs', 'Bourrache', 'bourrache'),
('fleurs', 'Capucine', 'capucine'),
('fleurs', 'Chrysantheme', 'chrysantheme'),
('fleurs', 'Edelweiss', 'edelweiss'),
('fleurs', 'Freesia', 'freesia'),
('fleurs', 'Gardenia', 'gardenia'),
('fleurs', 'Glycine', 'glycine'),
('fleurs', 'Hibiscus', 'hibiscus'),
('fleurs', 'Jacinthe', 'jacinthe'),
('fleurs', 'Myosotis', 'myosotis'),
('fleurs', 'Oeillet', 'oeillet'),
('fleurs', 'Primevere', 'primevere'),
('fleurs', 'Renoncule', 'renoncule'),
('fleurs', 'Rhododendron', 'rhododendron'),
('fleurs', 'Verveine', 'verveine'),
('fleurs', 'Fuchsia', 'fuchsia'),
('fleurs', 'Bruyere', 'bruyere'),
('fleurs', 'Aster', 'aster'),
('fleurs', 'Bleuet', 'bleuet'),
('fleurs', 'Acacia', 'acacia'),
('fleurs', 'Achillee', 'achillee'),
('fleurs', 'Agapanthe', 'agapanthe'),
('fleurs', 'Ajonc', 'ajonc'),
('fleurs', 'Alstroemeria', 'alstroemeria'),
('fleurs', 'Amarante', 'amarante'),
('fleurs', 'Amaryllis', 'amaryllis'),
('fleurs', 'Arnica', 'arnica'),
('fleurs', 'Belladone', 'belladone'),
('fleurs', 'Belle de jour', 'belle de jour'),
('fleurs', 'Belle de nuit', 'belle de nuit'),
('fleurs', 'Bouton d or', 'bouton d or'),
('fleurs', 'Bouvardia', 'bouvardia'),
('fleurs', 'Bouton de rose', 'bouton de rose'),
('fleurs', 'Calla', 'calla'),
('fleurs', 'Campanule', 'campanule'),
('fleurs', 'Clematite', 'clematite'),
('fleurs', 'Cosmos', 'cosmos'),
('fleurs', 'Crocus', 'crocus'),
('fleurs', 'Digitale', 'digitale'),
('fleurs', 'Echinacea', 'echinacea'),
('fleurs', 'Eglantine', 'eglantine'),
('fleurs', 'Euphorbe', 'euphorbe'),
('fleurs', 'Glaieul', 'glaieul'),
('fleurs', 'Gueule de loup', 'gueule de loup'),
('fleurs', 'Helianthe', 'helianthe'),
('fleurs', 'Hellebore', 'hellebore'),
('fleurs', 'Immortelle', 'immortelle'),
('fleurs', 'Ipomee', 'ipomee'),
('fleurs', 'Lavatera', 'lavatera'),
('fleurs', 'Lobelia', 'lobelia'),
('fleurs', 'Lupin', 'lupin'),
('fleurs', 'Magnolia', 'magnolia'),
('fleurs', 'Mimosa', 'mimosa'),
('fleurs', 'Monarde', 'monarde'),
('fleurs', 'Muflier', 'muflier'),
('fleurs', 'Nigelle', 'nigelle'),
('fleurs', 'Pensee', 'pensee'),
('fleurs', 'Perce neige', 'perce neige'),
('fleurs', 'Petunia', 'petunia'),
('fleurs', 'Phlox', 'phlox'),
('fleurs', 'Pois de senteur', 'pois de senteur'),
('fleurs', 'Protea', 'protea'),
('fleurs', 'Reine marguerite', 'reine marguerite'),
('fleurs', 'Rose tremiere', 'rose tremiere'),
('fleurs', 'Souci', 'souci'),
('fleurs', 'Spiree', 'spiree'),
('fleurs', 'Statice', 'statice'),
('fleurs', 'Sterlitzia', 'sterlitzia'),
('fleurs', 'Veronique', 'veronique'),
('fleurs', 'Zinnia', 'zinnia'),
('fleurs', 'Yucca', 'yucca'),
('fleurs', 'Mahonia', 'mahonia'),
('fleurs', 'Ancolie', 'ancolie'),
('fleurs', 'Coreopsis', 'coreopsis'),
('fleurs', 'Gaillarde', 'gaillarde'),
('fleurs', 'Linotte', 'linotte'),
('fleurs', 'Liseron', 'liseron'),
('fleurs', 'Pervenche', 'pervenche'),
('fleurs', 'Scabieuse', 'scabieuse'),
('fleurs', 'Trefle', 'trefle'),

('emotions', 'Colere noire', 'colere noire'),
('emotions', 'Tendresse', 'tendresse'),
('emotions', 'Timidite', 'timidite'),
('emotions', 'Gene', 'gene'),
('emotions', 'Panique', 'panique'),
('emotions', 'Terreur', 'terreur'),
('emotions', 'Rage', 'rage'),
('emotions', 'Ennui', 'ennui'),
('emotions', 'Satisfaction', 'satisfaction'),
('emotions', 'Bonheur', 'bonheur'),
('emotions', 'Excitation', 'excitation'),
('emotions', 'Detresse', 'detresse'),
('emotions', 'Deception', 'deception'),
('emotions', 'Remords', 'remords'),
('emotions', 'Confusion', 'confusion'),
('emotions', 'Enthousiasme', 'enthousiasme'),
('emotions', 'Soulagement profond', 'soulagement profond'),
('emotions', 'Fascination', 'fascination'),
('emotions', 'Affection', 'affection'),
('emotions', 'Pitie', 'pitie'),
('emotions', 'Agacement', 'agacement'),
('emotions', 'Agonie', 'agonie'),
('emotions', 'Alegresse', 'alegresse'),
('emotions', 'Alienation', 'alienation'),
('emotions', 'Amertume', 'amertume'),
('emotions', 'Angoisse', 'angoisse'),
('emotions', 'Apaisement', 'apaisement'),
('emotions', 'Apathie', 'apathie'),
('emotions', 'Attachement', 'attachement'),
('emotions', 'Attirance', 'attirance'),
('emotions', 'Beatitude', 'beatitude'),
('emotions', 'Chagrin', 'chagrin'),
('emotions', 'Choc', 'choc'),
('emotions', 'Colere froide', 'colere froide'),
('emotions', 'Confiance', 'confiance'),
('emotions', 'Contentement', 'contentement'),
('emotions', 'Crainte', 'crainte'),
('emotions', 'Curiosite', 'curiosite'),
('emotions', 'Decouragement', 'decouragement'),
('emotions', 'Desarroi', 'desarroi'),
('emotions', 'Desespoir', 'desespoir'),
('emotions', 'Desir', 'desir'),
('emotions', 'Determination', 'determination'),
('emotions', 'Embarras', 'embarras'),
('emotions', 'Emerveillement', 'emerveillement'),
('emotions', 'Empathie', 'empathie'),
('emotions', 'Envie', 'envie'),
('emotions', 'Epuisement', 'epuisement'),
('emotions', 'Exasperation', 'exasperation'),
('emotions', 'Extase', 'extase'),
('emotions', 'Ferveur', 'ferveur'),
('emotions', 'Fou rire', 'fou rire'),
('emotions', 'Fureur', 'fureur'),
('emotions', 'Gaiete', 'gaiete'),
('emotions', 'Grief', 'grief'),
('emotions', 'Inquietude', 'inquietude'),
('emotions', 'Irritation', 'irritation'),
('emotions', 'Isolement', 'isolement'),
('emotions', 'Legerete', 'legerete'),
('emotions', 'Liberation', 'liberation'),
('emotions', 'Malaise', 'malaise'),
('emotions', 'Mepris', 'mepris'),
('emotions', 'Motivation', 'motivation'),
('emotions', 'Nervosite', 'nervosite'),
('emotions', 'Optimisme', 'optimisme'),
('emotions', 'Passion', 'passion'),
('emotions', 'Plenitude', 'plenitude'),
('emotions', 'Rancoeur', 'rancoeur'),
('emotions', 'Reconnaissance', 'reconnaissance'),
('emotions', 'Regret', 'regret'),
('emotions', 'Revolte', 'revolte'),
('emotions', 'Securite', 'securite'),
('emotions', 'Sensibilite', 'sensibilite'),
('emotions', 'Solitude', 'solitude'),
('emotions', 'Souci', 'souci'),
('emotions', 'Stupeur', 'stupeur'),
('emotions', 'Sympathie', 'sympathie'),
('emotions', 'Vexation', 'vexation'),
('emotions', 'Vulnerabilite', 'vulnerabilite'),

('vetements', 'Debardeur', 'debardeur'),
('vetements', 'Polo', 'polo'),
('vetements', 'Doudoune', 'doudoune'),
('vetements', 'Kway', 'kway'),
('vetements', 'Anorak', 'anorak'),
('vetements', 'Combinaison', 'combinaison'),
('vetements', 'Salopette', 'salopette'),
('vetements', 'Legging', 'legging'),
('vetements', 'Collant', 'collant'),
('vetements', 'Pantoufles', 'pantoufles'),
('vetements', 'Mocassins', 'mocassins'),
('vetements', 'Bottes', 'bottes'),
('vetements', 'Espadrilles', 'espadrilles'),
('vetements', 'Moufles', 'moufles'),
('vetements', 'Sous pull', 'sous pull'),
('vetements', 'Brassiere', 'brassiere'),
('vetements', 'Poncho', 'poncho'),
('vetements', 'Kimono', 'kimono'),
('vetements', 'Peignoir', 'peignoir'),
('vetements', 'Costume', 'costume'),

('boissons', 'The glace', 'the glace'),
('boissons', 'Jus citron', 'jus citron'),
('boissons', 'Jus peche', 'jus peche'),
('boissons', 'Jus poire', 'jus poire'),
('boissons', 'Jus fraise', 'jus fraise'),
('boissons', 'Jus abricot', 'jus abricot'),
('boissons', 'Jus pamplemousse', 'jus pamplemousse'),
('boissons', 'Jus cerise', 'jus cerise'),
('boissons', 'Diabolo grenadine', 'diabolo grenadine'),
('boissons', 'Diabolo menthe', 'diabolo menthe'),
('boissons', 'Frappe', 'frappe'),
('boissons', 'Latte', 'latte'),
('boissons', 'Espresso', 'espresso'),
('boissons', 'Moka', 'moka'),
('boissons', 'Macchiato', 'macchiato'),
('boissons', 'Ricore', 'ricore'),
('boissons', 'Seven Up', 'seven up'),
('boissons', 'Dr Pepper', 'dr pepper'),
('boissons', 'Canada Dry', 'canada dry'),
('boissons', 'Cristaline', 'cristaline'),

('desserts', 'Paris brest', 'paris brest'),
('desserts', 'Chouquette', 'chouquette'),
('desserts', 'Religieuse', 'religieuse'),
('desserts', 'Tarte au citron', 'tarte au citron'),
('desserts', 'Tarte aux pommes', 'tarte aux pommes'),
('desserts', 'Foret noire', 'foret noire'),
('desserts', 'Baba au rhum', 'baba au rhum'),
('desserts', 'Creme brulee', 'creme brulee'),
('desserts', 'Ile flottante', 'ile flottante'),
('desserts', 'Riz au lait', 'riz au lait'),
('desserts', 'Compote', 'compote'),
('desserts', 'Pain perdu', 'pain perdu'),
('desserts', 'Charlotte', 'charlotte'),
('desserts', 'Mochi', 'mochi'),
('desserts', 'Canneles', 'canneles'),
('desserts', 'Sundae', 'sundae'),
('desserts', 'Muffin', 'muffin'),
('desserts', 'Cupcake', 'cupcake'),
('desserts', 'Pecan pie', 'pecan pie'),
('desserts', 'Baklava', 'baklava'),

('objets_maison', 'Placard', 'placard'),
('objets_maison', 'Commode', 'commode'),
('objets_maison', 'Tabouret', 'tabouret'),
('objets_maison', 'Fauteuil', 'fauteuil'),
('objets_maison', 'Chevet', 'chevet'),
('objets_maison', 'Drap', 'drap'),
('objets_maison', 'Serviette', 'serviette'),
('objets_maison', 'Torchon', 'torchon'),
('objets_maison', 'Marmite', 'marmite'),
('objets_maison', 'Passoire', 'passoire'),
('objets_maison', 'Spatule', 'spatule'),
('objets_maison', 'Louche', 'louche'),
('objets_maison', 'Bouilloire', 'bouilloire'),
('objets_maison', 'Grille pain', 'grille pain'),
('objets_maison', 'Mixeur', 'mixeur'),
('objets_maison', 'Poubelle', 'poubelle'),
('objets_maison', 'Pinceau', 'pinceau'),
('objets_maison', 'Savon', 'savon'),
('objets_maison', 'Cintre', 'cintre'),
('objets_maison', 'Panier', 'panier'),

('cinema', 'Batman', 'batman'),
('cinema', 'Superman', 'superman'),
('cinema', 'Spiderman', 'spiderman'),
('cinema', 'Deadpool', 'deadpool'),
('cinema', 'Terminator', 'terminator'),
('cinema', 'Ratatouille', 'ratatouille'),
('cinema', 'Cars', 'cars'),
('cinema', 'Toy Story', 'toy story'),
('cinema', 'Frozen', 'frozen'),
('cinema', 'Memento', 'memento'),
('cinema', 'Seven', 'seven'),
('cinema', 'Heat', 'heat'),
('cinema', 'Blade Runner', 'blade runner'),
('cinema', 'Jaws', 'jaws'),
('cinema', 'Le Roi Lion', 'le roi lion'),
('cinema', 'Aladdin', 'aladdin'),
('cinema', 'Hercule', 'hercule'),
('cinema', 'The Mask', 'the mask'),
('cinema', 'Taken', 'taken'),
('cinema', 'Twilight', 'twilight'),
('cinema', 'Le Seigneur des Anneaux', 'le seigneur des anneaux'),
('cinema', 'Le Retour du Roi', 'le retour du roi'),
('cinema', 'Les Deux Tours', 'les deux tours'),
('cinema', 'La Communaute de l Anneau', 'la communaute de l anneau'),
('cinema', 'Harry Potter', 'harry potter'),
('cinema', 'La Pierre Philosophale', 'la pierre philosophale'),
('cinema', 'La Chambre des Secrets', 'la chambre des secrets'),
('cinema', 'Le Prisonnier d Azkaban', 'le prisonnier d azkaban'),
('cinema', 'La Coupe de Feu', 'la coupe de feu'),
('cinema', 'L Ordre du Phenix', 'l ordre du phenix'),
('cinema', 'Le Prince de Sang Mele', 'le prince de sang mele'),
('cinema', 'Les Reliques de la Mort', 'les reliques de la mort'),
('cinema', 'Jurassic Park', 'jurassic park'),
('cinema', 'Le Monde Perdu', 'le monde perdu'),
('cinema', 'Jurassic World', 'jurassic world'),
('cinema', 'E T', 'e t'),
('cinema', 'Indiana Jones', 'indiana jones'),
('cinema', 'Les Aventuriers de l Arche Perdue', 'les aventuriers de l arche perdue'),
('cinema', 'Le Temple Maudit', 'le temple maudit'),
('cinema', 'La Derniere Croisade', 'la derniere croisade'),
('cinema', 'Pirates des Caraibes', 'pirates des caraibes'),
('cinema', 'La Malediction du Black Pearl', 'la malediction du black pearl'),
('cinema', 'Le Secret du Coffre Maudit', 'le secret du coffre maudit'),
('cinema', 'Jusqu au Bout du Monde', 'jusqu au bout du monde'),
('cinema', 'Mission Impossible', 'mission impossible'),
('cinema', 'Fallout', 'fallout'),
('cinema', 'Top Gun', 'top gun'),
('cinema', 'Top Gun Maverick', 'top gun maverick'),
('cinema', 'Mad Max', 'mad max'),
('cinema', 'Fury Road', 'fury road'),
('cinema', 'Le Silence des Agneaux', 'le silence des agneaux'),
('cinema', 'Psychose', 'psychose'),
('cinema', 'Shining', 'shining'),
('cinema', 'Orange Mecanique', 'orange mecanique'),
('cinema', '2001 Odyssee de l Espace', '2001 odyssee de l espace'),
('cinema', 'Apocalypse Now', 'apocalypse now'),
('cinema', 'Taxi Driver', 'taxi driver'),
('cinema', 'Goodfellas', 'goodfellas'),
('cinema', 'Scarface', 'scarface'),
('cinema', 'Reservoir Dogs', 'reservoir dogs'),
('cinema', 'Kill Bill', 'kill bill'),
('cinema', 'Inglourious Basterds', 'inglourious basterds'),
('cinema', 'Django Unchained', 'django unchained'),
('cinema', 'Once Upon a Time in Hollywood', 'once upon a time in hollywood'),
('cinema', 'La La Land', 'la la land'),
('cinema', 'Moonlight', 'moonlight'),
('cinema', 'Birdman', 'birdman'),
('cinema', 'The Grand Budapest Hotel', 'the grand budapest hotel'),
('cinema', 'The French Dispatch', 'the french dispatch'),
('cinema', 'No Country for Old Men', 'no country for old men'),
('cinema', 'There Will Be Blood', 'there will be blood'),
('cinema', 'The Social Network', 'the social network'),
('cinema', 'Gone Girl', 'gone girl'),
('cinema', 'The Curious Case of Benjamin Button', 'the curious case of benjamin button'),
('cinema', 'Zodiac', 'zodiac'),
('cinema', 'Le Fabuleux Destin d Amelie Poulain', 'le fabuleux destin d amelie poulain'),
('cinema', 'Les Intouchables', 'les intouchables'),
('cinema', 'La Haine', 'la haine'),
('cinema', 'Le Diner de Cons', 'le diner de cons'),
('cinema', 'OSS 117', 'oss 117'),
('cinema', 'Asterix et Obelix', 'asterix et obelix'),
('cinema', 'Le Prenom', 'le prenom'),
('cinema', 'Le Cinquieme Element', 'le cinquieme element'),
('cinema', 'Leon', 'leon'),
('cinema', 'Nikita', 'nikita'),
('cinema', 'The Dark Knight', 'the dark knight'),
('cinema', 'Batman Begins', 'batman begins'),
('cinema', 'The Batman', 'the batman'),
('cinema', 'Man of Steel', 'man of steel'),
('cinema', 'Iron Man', 'iron man'),
('cinema', 'Thor', 'thor'),
('cinema', 'Black Panther', 'black panther'),
('cinema', 'Doctor Strange', 'doctor strange'),
('cinema', 'Guardians of the Galaxy', 'guardians of the galaxy'),
('cinema', 'Avengers Endgame', 'avengers endgame'),
('cinema', 'Avengers Infinity War', 'avengers infinity war'),
('cinema', 'Captain America', 'captain america'),
('cinema', 'Black Widow', 'black widow'),
('cinema', 'Wonder Woman', 'wonder woman'),
('cinema', 'Aquaman', 'aquaman'),
('cinema', 'Joker Folie a Deux', 'joker folie a deux'),
('cinema', 'Le Voyage de Chihiro', 'le voyage de chihiro'),
('cinema', 'Princesse Mononoke', 'princesse mononoke'),
('cinema', 'Mon Voisin Totoro', 'mon voisin totoro'),
('cinema', 'Le Chateau Ambulant', 'le chateau ambulant'),
('cinema', 'Ponyo', 'ponyo'),
('cinema', 'Kiki la Petite Sorciere', 'kiki la petite sorciere'),
('cinema', 'Akira', 'akira'),
('cinema', 'Your Name', 'your name'),
('cinema', 'Weathering with You', 'weathering with you'),
('cinema', 'Le Tombeau des Lucioles', 'le tombeau des lucioles'),
('cinema', 'Wall E', 'wall e'),
('cinema', 'Monstres et Compagnie', 'monstres et compagnie'),
('cinema', 'Vice Versa', 'vice versa'),
('cinema', 'Le Monde de Nemo', 'le monde de nemo'),
('cinema', 'Le Monde de Dory', 'le monde de dory'),
('cinema', 'Les Indestructibles', 'les indestructibles'),
('cinema', 'Encanto', 'encanto'),
('cinema', 'Vaiana', 'vaiana'),
('cinema', 'Zootopie', 'zootopie'),
('cinema', 'Kung Fu Panda', 'kung fu panda'),
('cinema', 'Dragons', 'dragons'),
('cinema', 'Moi Moche et Mechant', 'moi moche et mechant'),
('cinema', 'Minions', 'minions'),
('cinema', 'Madagascar', 'madagascar'),
('cinema', 'L Age de Glace', 'l age de glace'),
('cinema', 'Le Chat Potte', 'le chat potte'),
('cinema', 'Bob l Eponge le Film', 'bob l eponge le film'),
('cinema', 'Scream', 'scream'),
('cinema', 'Conjuring', 'conjuring'),
('cinema', 'Saw', 'saw'),
('cinema', 'Insidious', 'insidious'),
('cinema', 'Get Out', 'get out'),
('cinema', 'Us', 'us'),
('cinema', 'Nope', 'nope'),
('cinema', 'A Quiet Place', 'a quiet place'),
('cinema', 'The Exorcist', 'the exorcist'),
('cinema', 'Hereditary', 'hereditary'),
('cinema', 'Midsommar', 'midsommar'),
('cinema', 'The Ring', 'the ring'),
('cinema', 'The Blair Witch Project', 'the blair witch project'),
('cinema', 'Final Destination', 'final destination'),
('cinema', 'Le Sixieme Sens', 'le sixieme sens'),
('cinema', 'The Truman Show', 'the truman show'),
('cinema', 'Cast Away', 'cast away'),
('cinema', 'Seul au Monde', 'seul au monde'),
('cinema', 'Le Loup de Wall Street', 'le loup de wall street'),
('cinema', 'Le Terminal', 'le terminal'),
('cinema', 'Argo', 'argo'),
('cinema', 'The Departed', 'the departed'),
('cinema', 'Le Prestige', 'le prestige'),
('cinema', 'Tenet', 'tenet'),
('cinema', 'Insomnia', 'insomnia'),
('cinema', 'The Revenant', 'the revenant'),
('cinema', 'Shutter Island', 'shutter island'),
('cinema', 'The Wolf of Wall Street', 'the wolf of wall street'),
('cinema', 'The Aviator', 'the aviator'),
('cinema', 'Les Affranchis', 'les affranchis'),
('cinema', 'Le Parrain 2', 'le parrain 2'),
('cinema', 'Le Parrain 3', 'le parrain 3'),
('cinema', 'Casino', 'casino'),
('cinema', 'American Beauty', 'american beauty'),
('cinema', 'American Psycho', 'american psycho'),
('cinema', 'Donnie Darko', 'donnie darko'),
('cinema', 'Drive', 'drive'),
('cinema', 'Nightcrawler', 'nightcrawler'),
('cinema', 'Whisky a Gogo', 'whisky a gogo'),
('cinema', 'Le Samourai', 'le samourai'),
('cinema', 'Citizen Kane', 'citizen kane'),
('cinema', 'Ben Hur', 'ben hur'),
('cinema', 'Lawrence of Arabia', 'lawrence of arabia'),
('cinema', 'Le Bon la Brute et le Truand', 'le bon la brute et le truand'),
('cinema', 'Il etait une Fois dans l Ouest', 'il etait une fois dans l ouest'),
('cinema', 'Le Bonheur est dans le Pre', 'le bonheur est dans le pre'),

('jeux_video', 'Roblox', 'roblox'),
('jeux_video', 'Rocket League', 'rocket league'),
('jeux_video', 'Among Us', 'among us'),
('jeux_video', 'Terraria', 'terraria'),
('jeux_video', 'Stardew Valley', 'stardew valley'),
('jeux_video', 'Animal Crossing', 'animal crossing'),
('jeux_video', 'Splatoon', 'splatoon'),
('jeux_video', 'Resident Evil', 'resident evil'),
('jeux_video', 'Silent Hill', 'silent hill'),
('jeux_video', 'God of War', 'god of war'),
('jeux_video', 'The Witcher', 'the witcher'),
('jeux_video', 'Fall Guys', 'fall guys'),
('jeux_video', 'Diablo', 'diablo'),
('jeux_video', 'Starcraft', 'starcraft'),
('jeux_video', 'The Sims', 'the sims'),
('jeux_video', 'Monopoly Go', 'monopoly go'),
('jeux_video', 'Brawl Stars', 'brawl stars'),
('jeux_video', 'Clash Royale', 'clash royale'),
('jeux_video', 'Clash of Clans', 'clash of clans'),
('jeux_video', 'Tekken', 'tekken'),

('sciences', 'Calcul', 'calcul'),
('sciences', 'Geometrie', 'geometrie'),
('sciences', 'Analyse', 'analyse'),
('sciences', 'Probabilites', 'probabilites'),
('sciences', 'Logique', 'logique'),
('sciences', 'Mecanique', 'mecanique'),
('sciences', 'Optique', 'optique'),
('sciences', 'Electronique', 'electronique'),
('sciences', 'Electromagnetisme', 'electromagnetisme'),
('sciences', 'Sismologie', 'sismologie'),
('sciences', 'Volcanologie', 'volcanologie'),
('sciences', 'Paleontologie', 'paleontologie'),
('sciences', 'Virologie', 'virologie'),
('sciences', 'Immunologie', 'immunologie'),
('sciences', 'Parasitologie', 'parasitologie'),
('sciences', 'Agronomie', 'agronomie'),
('sciences', 'Hydrologie', 'hydrologie'),
('sciences', 'Algorithmique', 'algorithmique'),
('sciences', 'Data science', 'data science'),
('sciences', 'Cybernetique', 'cybernetique'),

('musique', 'Dubstep', 'dubstep'),
('musique', 'Hard rock', 'hard rock'),
('musique', 'Punk', 'punk'),
('musique', 'Punk rock', 'punk rock'),
('musique', 'Gospel', 'gospel'),
('musique', 'Bossa nova', 'bossa nova'),
('musique', 'Samba', 'samba'),
('musique', 'RaI', 'rai'),
('musique', 'Variete francaise', 'variete francaise'),
('musique', 'Chanson francaise', 'chanson francaise'),
('musique', 'Electro swing', 'electro swing'),
('musique', 'Trance', 'trance'),
('musique', 'Ambient', 'ambient'),
('musique', 'Indie', 'indie'),
('musique', 'Synthwave', 'synthwave'),
('musique', 'New wave', 'new wave'),
('musique', 'Dancehall', 'dancehall'),
('musique', 'Dance', 'dance'),
('musique', 'Jpop', 'jpop'),
('musique', 'Reggaeton', 'reggaeton')
) AS w(slug, label, normalized_label)
ON c.slug = w.slug;

INSERT INTO daily_categories (date, category_id)
SELECT
CURRENT_DATE,
picked.id
FROM (
SELECT c.id
FROM categories c
WHERE c.active = true
ORDER BY c.slug
OFFSET (SELECT MOD(EXTRACT(EPOCH FROM CURRENT_DATE::timestamp)::bigint / 86400, GREATEST(COUNT(*), 1))::int FROM categories WHERE active = true)
LIMIT 1
) AS picked
ON CONFLICT (date) DO UPDATE
SET category_id = EXCLUDED.category_id;
